// This file was auto-generated by Fern from our API Definition.

export interface GetMarketFeeResponse {
    error?: (string | null) | undefined;
    /** Taker fee percentage */
    taker?: string | undefined;
    /** Maker fee percentage */
    maker?: string | undefined;
    /** Default effective futures taker fee rate. The system returns the lower value between the custom fee (if assigned) and the default market fee. */
    futures_taker?: string | undefined;
    /** Default effective futures maker fee rate. The system returns the lower value between the custom fee (if assigned) and the default market fee. */
    futures_maker?: string | undefined;
    /** Per-market fee overrides, keyed by market name. Each value contains the market's custom `taker` and `maker` rates. */
    custom_fee?: Record<string, GetMarketFeeResponse.CustomFee.Value> | undefined;
}

export namespace GetMarketFeeResponse {
    export namespace CustomFee {
        export interface Value {
            /** Custom taker fee percentage for the market */
            taker?: string | undefined;
            /** Custom maker fee percentage for the market */
            maker?: string | undefined;
        }
    }
}
