// This file was auto-generated by Fern from our API Definition.

export interface GetMarketFeeResponse {
    error?: (string | null) | undefined;
    /** Taker fee percentage */
    taker?: string | undefined;
    /** Maker fee percentage */
    maker?: string | undefined;
    /** Effective futures taker fee rate for the specified market. The system returns the lower value between the custom fee (if assigned) and the default market fee. */
    futures_taker?: string | undefined;
    /** Effective futures maker fee rate for the specified market. The system returns the lower value between the custom fee (if assigned) and the default market fee. */
    futures_maker?: string | undefined;
}
