// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         request: "{{request}}",
 *         nonce: 1594297865000
 *     }
 */
export interface GetMyCodesRequest {
    /** LIMIT is a special clause used to limit records a particular query can return. */
    limit?: number;
    /** Use the OFFSET clause to return entries starting from a particular line. */
    offset?: number;
    /** Request signature */
    request: string;
    /** Unique request identifier */
    nonce: number;
}
