// This file was auto-generated by Fern from our API Definition.

export interface CreateMiningWatcherLinkResponse {
    data?: CreateMiningWatcherLinkResponse.Data | undefined;
}

export namespace CreateMiningWatcherLinkResponse {
    export interface Data {
        id?: string | undefined;
        link?: string | undefined;
        liveUntil?: (number | null) | undefined;
        createdAt?: number | undefined;
    }
}
