// This file was auto-generated by Fern from our API Definition.

export interface CreateMiningAccountResponse {
    data?: CreateMiningAccountResponse.Data | undefined;
}

export namespace CreateMiningAccountResponse {
    export interface Data {
        /** Created mining account name */
        name?: string | undefined;
        /** Account creation timestamp (Unix time) */
        createdAt?: number | undefined;
    }
}
