// This file was auto-generated by Fern from our API Definition.

export interface GetMiningAccountsResponse {
    data?: GetMiningAccountsResponse.Data.Item[] | undefined;
    limit?: number | undefined;
    offset?: number | undefined;
}

export namespace GetMiningAccountsResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            /** Mining account name */
            name?: string | undefined;
            /** Account creation timestamp (Unix time) */
            createdAt?: number | undefined;
        }
    }
}
