// This file was auto-generated by Fern from our API Definition.

export interface GetMiningPayoutDestinationResponse {
    /** Payout destination type */
    payoutDestination?: GetMiningPayoutDestinationResponse.PayoutDestination | undefined;
    /** External BTC address (null if destination is main_balance) */
    externalAddress?: (string | null) | undefined;
}

export namespace GetMiningPayoutDestinationResponse {
    /** Payout destination type */
    export const PayoutDestination = {
        MainBalance: "main_balance",
        ExternalAddress: "external_address",
    } as const;
    export type PayoutDestination = (typeof PayoutDestination)[keyof typeof PayoutDestination];
}
