// This file was auto-generated by Fern from our API Definition.

export interface GetMiningWorkerNamesResponse {
    data?: GetMiningWorkerNamesResponse.Data | undefined;
    limit?: number | undefined;
    offset?: number | undefined;
}

export namespace GetMiningWorkerNamesResponse {
    export interface Data {
        workers?: string[] | undefined;
    }
}
