// This file was auto-generated by Fern from our API Definition.

export interface GetMiningHashrateResponse {
    data?: GetMiningHashrateResponse.Data | undefined;
}

export namespace GetMiningHashrateResponse {
    export interface Data {
        account?: string | undefined;
        hashrate?: Data.Hashrate.Item[] | undefined;
    }

    export namespace Data {
        export type Hashrate = Hashrate.Item[];

        export namespace Hashrate {
            export interface Item {
                timestamp?: number | undefined;
                hashrate?: string | undefined;
            }
        }
    }
}
