// This file was auto-generated by Fern from our API Definition.

export interface SetMiningPayoutDestinationResponse {
    payoutDestination?: SetMiningPayoutDestinationResponse.PayoutDestination | undefined;
    externalAddress?: (string | null) | undefined;
}

export namespace SetMiningPayoutDestinationResponse {
    export const PayoutDestination = {
        MainBalance: "main_balance",
        ExternalAddress: "external_address",
    } as const;
    export type PayoutDestination = (typeof PayoutDestination)[keyof typeof PayoutDestination];
}
