// This file was auto-generated by Fern from our API Definition.

export interface Asset {
    /** Full name of cryptocurrency */
    name?: string | undefined;
    /** Unique ID of cryptocurrency assigned by Unified Cryptoasset ID, 0 if unknown */
    unified_cryptoasset_id?: number | undefined;
    /** Indicates withdrawal status (enabled or disabled) */
    can_withdraw?: boolean | undefined;
    /** Indicates deposit status (enabled or disabled) */
    can_deposit?: boolean | undefined;
    /** Minimum withdrawal amount for the asset */
    min_withdraw?: string | undefined;
    /** Maximum withdrawal amount for the asset */
    max_withdraw?: string | undefined;
    /** Maker fee expressed as a direct percentage value (e.g., "0.1" means 0.1%). Note: GET /api/v4/public/markets expresses the same fee as a decimal ratio (e.g., "0.001" = 0.1%) — the formats differ between endpoints. */
    maker_fee?: string | undefined;
    /** Taker fee expressed as a direct percentage value (e.g., "0.1" means 0.1%). Note: GET /api/v4/public/markets expresses the same fee as a decimal ratio (e.g., "0.001" = 0.1%) — the formats differ between endpoints. */
    taker_fee?: string | undefined;
    /** Min deposit amount */
    min_deposit?: string | undefined;
    /** Max deposit amount; omitted if no limit, 0 if unlimited */
    max_deposit?: string | undefined;
    /** Max number of digits to the right of the decimal point */
    currency_precision?: number | undefined;
    /** Indicates whether the asset requires a memo address */
    is_memo?: boolean | undefined;
    /** Indicates whether the asset requires a memo for deposits and withdrawals */
    memo?: Asset.Memo | undefined;
    /** Currency networks */
    networks?: Asset.Networks | undefined;
    /** Currency limits by each network */
    limits?: Asset.Limits | undefined;
    /** Required blockchain confirmations for deposits, mapped by network name (e.g., {"BTC": 2, "ERC20": 20}). Absent for fiat currencies, demo assets, and internal exchange tokens (e.g., UAH, EUR, DBTC, DUSDT). Individual network keys may also be absent if a network was historically supported but is currently disabled. */
    confirmations?: Record<string, number> | undefined;
    /** Payment provider identifiers for fiat assets (e.g., VISAMASTER, ADVCASH, GEOPAY). Use these identifiers as the network parameter value when making fiat deposits or withdrawals via the API — equivalent to network codes such as ERC20 or TRC20 for crypto assets. */
    providers?: Asset.Providers | undefined;
}

export namespace Asset {
    /**
     * Indicates whether the asset requires a memo for deposits and withdrawals
     */
    export interface Memo {
        deposit?: boolean | undefined;
        withdraw?: boolean | undefined;
    }

    /**
     * Currency networks
     */
    export interface Networks {
        /** Networks available for depositing. Absent when deposits are disabled for the asset (can_deposit: false). Examples of assets where the field may be absent: AMB, AVA, A, KZT. */
        deposits?: string[] | undefined;
        /** Networks available for withdrawing. Absent when withdrawals are disabled for the asset (can_withdraw: false). Examples: AVA, A (Vaulta). */
        withdraws?: string[] | undefined;
        /** Default network used when no specific network is selected by the user. Absent when multiple networks exist but no explicit default priority has been configured (e.g., AGRS, ANKR, APE, POL). */
        default?: string | undefined;
    }

    /**
     * Currency limits by each network
     */
    export interface Limits {
        /** Deposits limits */
        deposit?: Record<string, Limits.Deposit.Value> | undefined;
        /** Withdraws limits */
        withdraw?: Record<string, Limits.Withdraw.Value> | undefined;
    }

    export namespace Limits {
        export namespace Deposit {
            export interface Value {
                min?: string | undefined;
                max?: string | undefined;
            }
        }

        export namespace Withdraw {
            export interface Value {
                min?: string | undefined;
                max?: string | undefined;
            }
        }
    }

    /**
     * Payment provider identifiers for fiat assets (e.g., VISAMASTER, ADVCASH, GEOPAY). Use these identifiers as the network parameter value when making fiat deposits or withdrawals via the API — equivalent to network codes such as ERC20 or TRC20 for crypto assets.
     */
    export interface Providers {
        deposits?: string[] | undefined;
        withdraws?: string[] | undefined;
    }
}
