// This file was auto-generated by Fern from our API Definition.

export interface AuthorizeRequest {
    /** Unique request identifier */
    id: number;
    /** Method name. Fixed value: `authorize`. */
    method: AuthorizeRequest.Method;
    /** Array with WebSocket token and constant "public" string */
    params: unknown[];
}

export namespace AuthorizeRequest {
    /** Method name. Fixed value: `authorize`. */
    export const Method = {
        Authorize: "authorize",
    } as const;
    export type Method = (typeof Method)[keyof typeof Method];
}
