// This file was auto-generated by Fern from our API Definition.

export interface BalanceSpotUpdate {
    /** Update events have null id */
    id: unknown | null;
    /** Method name. Fixed value: `balanceSpot_update`. */
    method: "balanceSpot_update";
    /** Array containing balance updates for subscribed assets */
    params: Record<string, BalanceSpotUpdate.Params.Value>[];
}

export namespace BalanceSpotUpdate {
    export type Params = Params.Item[];

    export namespace Params {
        export type Value = Item;
        export interface Item {
            /** Amount available for trade */
            available?: string | undefined;
            /** Amount in active [orders](/glossary#orders) */
            freeze?: string | undefined;
        }
    }
}
