// This file was auto-generated by Fern from our API Definition.

export interface BalanceSpotResponse {
    /** Request identifier matching the request */
    id: number;
    /** Wallet balances by currency */
    result: Record<string, BalanceSpotResponse.Result.Value>;
    /** Error object (null on success) */
    error: unknown | null;
}

export namespace BalanceSpotResponse {
    export namespace Result {
        export interface Value {
            /** Amount available for trade */
            available?: string | undefined;
            /** Amount in active [orders](/glossary#orders) */
            freeze?: string | undefined;
        }
    }
}
