// This file was auto-generated by Fern from our API Definition.

export interface BalanceMarginSubscribe {
    /** Unique request identifier */
    id: number;
    /** Method name. Fixed value: `balanceMargin_subscribe`. */
    method: "balanceMargin_subscribe";
    /** Array of asset tickers to subscribe to */
    params: string[];
}
