// This file was auto-generated by Fern from our API Definition.

export interface BookTickerSubscribe {
    /** Unique request identifier */
    id: number;
    /** Method name. Fixed value: `bookTicker_subscribe`. */
    method: "bookTicker_subscribe";
    params: string[];
}
