// This file was auto-generated by Fern from our API Definition.

import type * as WhitebitApi from "../index.js";

export interface BookTickerUpdate {
    id: unknown | null;
    /** Method name. Fixed value: `bookTicker_update`. */
    method: "bookTicker_update";
    params: WhitebitApi.BookTickerUpdateData[];
}
