// This file was auto-generated by Fern from our API Definition.

/**
 * Book ticker update tuple with 8 elements:
 * - [0] Transaction time (Unix timestamp from matchengine)
 * - [1] Message time (Unix timestamp from websocket)
 * - [2] Market name
 * - [3] Update ID
 * - [4] Best bid price
 * - [5] Best bid amount
 * - [6] Best ask price
 * - [7] Best ask amount
 */
export type BookTickerUpdateData = unknown[];
