// This file was auto-generated by Fern from our API Definition.

export interface BorrowsEventsUpdate {
    /** Update events have null id */
    id: unknown | null;
    /** Method name. Fixed value: `borrowsAccountMargin_update`. */
    method: "borrowsAccountMargin_update";
    /**
     * Event tuple:
     * - [0] Event type (1=Margin call, 2=Liquidation)
     * - [1] Borrow object with all borrow details
     */
    params: unknown[];
}
