// This file was auto-generated by Fern from our API Definition.

export interface BorrowsSubscribe {
    /** Unique request identifier */
    id: number;
    /** Method name. Fixed value: `borrowsMargin_subscribe`. */
    method: BorrowsSubscribe.Method;
    /** Empty array for borrows subscription */
    params: unknown[];
}

export namespace BorrowsSubscribe {
    /** Method name. Fixed value: `borrowsMargin_subscribe`. */
    export const Method = {
        BorrowsMarginSubscribe: "borrowsMargin_subscribe",
    } as const;
    export type Method = (typeof Method)[keyof typeof Method];
}
