// This file was auto-generated by Fern from our API Definition.

export interface BorrowsEventsSubscribe {
    /** Unique request identifier */
    id: number;
    /** Method name. Fixed value: `borrowsAccountMargin_subscribe`. */
    method: BorrowsEventsSubscribe.Method;
    /** Empty array */
    params: unknown[];
}

export namespace BorrowsEventsSubscribe {
    /** Method name. Fixed value: `borrowsAccountMargin_subscribe`. */
    export const Method = {
        BorrowsAccountMarginSubscribe: "borrowsAccountMargin_subscribe",
    } as const;
    export type Method = (typeof Method)[keyof typeof Method];
}
