// This file was auto-generated by Fern from our API Definition.

import type * as WhitebitApi from "../index.js";

export interface BulkCancelOrderResponseItem {
    result?: (WhitebitApi.BulkCancelOrderResult | null) | undefined;
    error?: (WhitebitApi.ErrorResponse | null) | undefined;
}
