// This file was auto-generated by Fern from our API Definition.

/**
 * Acknowledgement that a single item was cancelled. The endpoint echoes the identifiers from the request item; full order state is not returned. Use the single Cancel order endpoint when post-cancel order state is required.
 */
export interface BulkCancelOrderResult {
    /** System-assigned order ID of the cancelled order. */
    orderId?: number | undefined;
    /** Client-defined order ID of the cancelled order, if one was set at order creation. */
    clientOrderId?: string | undefined;
    /** Trading pair of the cancelled order. Format: `BASE_QUOTE` (e.g. `BTC_USDT`). */
    market?: string | undefined;
}
