// This file was auto-generated by Fern from our API Definition.

export interface BulkOrderItem {
    side?: BulkOrderItem.Side | undefined;
    amount?: string | undefined;
    price?: string | undefined;
    market?: string | undefined;
    postOnly?: boolean | undefined;
    /**
     * Immediate-or-cancel (IOC) executes all or part of an order immediately and cancels any unfilled portion.
     *
     * IOC does not support `rpi=true` because RPI uses post-only behavior by design.
     * The API returns error code `37` when an order item sets both `ioc=true` and `rpi=true`.
     */
    ioc?: boolean | undefined;
    client_order_id?: string | undefined;
    /**
     * Enables Retail Price Improvement (RPI) mode.
     *
     * RPI orders use post-only behavior by design. An RPI order does not support `ioc=true`.
     * The API returns error code `37` when an order item sets both `rpi=true` and `ioc=true`.
     */
    rpi?: boolean | undefined;
}

export namespace BulkOrderItem {
    export const Side = {
        Buy: "buy",
        Sell: "sell",
    } as const;
    export type Side = (typeof Side)[keyof typeof Side];
}
