// This file was auto-generated by Fern from our API Definition.

export interface CandlesRequest {
    /** Unique request identifier */
    id: number;
    /** Method name. Fixed value: `candles_request`. */
    method: CandlesRequest.Method;
    /**
     * Query parameters:
     * - [0] Market name (e.g., ETH_BTC)
     * - [1] Start time (Unix timestamp)
     * - [2] End time (Unix timestamp)
     * - [3] Interval in seconds
     */
    params: unknown[];
}

export namespace CandlesRequest {
    /** Method name. Fixed value: `candles_request`. */
    export const Method = {
        CandlesRequest: "candles_request",
    } as const;
    export type Method = (typeof Method)[keyof typeof Method];
}
