// This file was auto-generated by Fern from our API Definition.

import type * as WhitebitApi from "../index.js";

export interface CandlesResponse {
    /** Request identifier matching the request */
    id: number;
    result: WhitebitApi.Candle[];
    error: unknown | null;
}
