// This file was auto-generated by Fern from our API Definition.

import type * as WhitebitApi from "../index.js";

export interface CandlesUpdate {
    id: unknown | null;
    /** Method name. Fixed value: `candles_update`. */
    method: "candles_update";
    params: WhitebitApi.Candle[];
}
