// This file was auto-generated by Fern from our API Definition.

/**
 * Candlestick data tuple with 8 elements:
 * - [0] Time (Unix timestamp)
 * - [1] Open price
 * - [2] Close price
 * - [3] High price
 * - [4] Low price
 * - [5] Volume in stock currency
 * - [6] Volume in deal currency (money)
 * - [7] Market pair name
 */
export type Candle = unknown[];
