// This file was auto-generated by Fern from our API Definition.

export interface CodeHistory {
    /** Code amount change (- is created, + is applied) */
    amount?: string | undefined;
    /** WhiteBIT code */
    code?: string | undefined;
    /** Code activation timestamp (for applied) or code creation timestamp (for created) */
    date?: number | undefined;
    /** Current code status */
    status?: string | undefined;
    /** Code [ticker](/glossary#ticker) */
    ticker?: string | undefined;
    /** Code external identifier */
    external_id?: string | undefined;
}
