// This file was auto-generated by Fern from our API Definition.

export interface ConvertHistoryResponse {
    records?: ConvertHistoryResponse.Records.Item[] | undefined;
    /** Total number of records */
    total?: number | undefined;
    /** Limit used in request */
    limit?: number | undefined;
    /** Offset used in request */
    offset?: number | undefined;
}

export namespace ConvertHistoryResponse {
    export type Records = Records.Item[];

    export namespace Records {
        export interface Item {
            /** Convert record ID */
            id?: string | undefined;
            /** Conversion timestamp */
            date?: number | undefined;
            /** Amount given */
            give?: string | undefined;
            /** Amount received */
            receive?: string | undefined;
            /** Conversion rate */
            rate?: string | undefined;
            path?: Item.Path.Item[] | undefined;
        }

        export namespace Item {
            export type Path = Path.Item[];

            export namespace Path {
                export interface Item {
                    from?: string | undefined;
                    to?: string | undefined;
                    rate?: string | undefined;
                }
            }
        }
    }
}
