// This file was auto-generated by Fern from our API Definition.

export interface ConvertEstimateResponse {
    /** Quote ID */
    id?: string | undefined;
    /** From currency */
    from?: string | undefined;
    /** To currency */
    to?: string | undefined;
    /** Amount to give */
    give?: string | undefined;
    /** Amount to receive */
    receive?: string | undefined;
    /** Conversion rate */
    rate?: string | undefined;
    /** Quote expiration timestamp */
    expireAt?: number | undefined;
}
