// This file was auto-generated by Fern from our API Definition.

export interface ConvertEstimateResponse {
    /** Quote ID */
    id?: string | undefined;
    /** From currency */
    from?: string | undefined;
    /** To currency */
    to?: string | undefined;
    /** Amount to give */
    give?: string | undefined;
    /** Amount to receive */
    receive?: string | undefined;
    /** Conversion rate expressed in the from→to direction: units of the 'to' currency received per one unit of the 'from' currency. Example: if from=BTC and to=USDT, a rate of "34299.76" means 1 BTC is worth approximately 34 299.76 USDT at the time of the quote. */
    rate?: string | undefined;
    /** Quote expiration timestamp */
    expireAt?: number | undefined;
}
