// This file was auto-generated by Fern from our API Definition.

export interface CreditLine {
    asset?: string | undefined;
    amount?: string | undefined;
    totalFunding?: string | undefined;
    currentLtv?: string | undefined;
    initialLtv?: string | undefined;
    marginCallLtv?: string | undefined;
    liquidationLtv?: string | undefined;
    createdAt?: number | undefined;
}
