// This file was auto-generated by Fern from our API Definition.

export interface DealsSubscribe {
    /** Unique request identifier */
    id: number;
    /** Method name. Fixed value: `deals_subscribe`. */
    method: "deals_subscribe";
    /** Array containing array of markets */
    params: string[][];
}
