// This file was auto-generated by Fern from our API Definition.

export interface DealsRequest {
    /** Unique request identifier */
    id: number;
    /** Method name. Fixed value: `deals_request`. */
    method: "deals_request";
    /**
     * Query parameters tuple:
     * - [0] Market name
     * - [1] Offset
     * - [2] Limit (max 100)
     */
    params: unknown[];
}
