// This file was auto-generated by Fern from our API Definition.

export interface DealsResponse {
    /** Request identifier matching the request */
    id: number;
    result: DealsResponse.Result;
    /** Error object (null on success) */
    error: unknown | null;
}

export namespace DealsResponse {
    export interface Result {
        /** Limit from request */
        limit?: number | undefined;
        /** Offset from request */
        offset?: number | undefined;
        records?: Result.Records.Item[] | undefined;
    }

    export namespace Result {
        export type Records = Records.Item[];

        export namespace Records {
            export interface Item {
                /** Deal time in Unix time */
                time?: number | undefined;
                /** Deal ID */
                id?: number | undefined;
                /** Side: 1=sell, 2=buy/bid */
                side?: number | undefined;
                /** Role: 1=[maker](/glossary#maker), 2=taker */
                role?: number | undefined;
                /** Deal price */
                price?: string | undefined;
                /** [Stock](/glossary#stock) amount */
                amount?: string | undefined;
                /** [Money](/glossary#money) amount */
                deal?: string | undefined;
                /** Deal fee expressed in asset in fee_asset */
                fee?: string | undefined;
                /** Order ID */
                order_id?: number | undefined;
                /** Counterparty Order ID */
                deal_order_id?: number | undefined;
                /** [Market](/glossary#market) */
                market?: string | undefined;
                /** Client Order ID */
                client_order_id?: string | undefined;
                /** Fee asset type */
                fee_asset?: string | undefined;
            }
        }
    }
}
