// This file was auto-generated by Fern from our API Definition.

export interface DepthUpdate {
    id: unknown | null;
    /** Method name. Fixed value: `depth_update`. */
    method: DepthUpdate.Method;
    /**
     * Update event parameters:
     * - [0] Full reload flag (true=full snapshot, false=incremental)
     * - [1] Order book data (DepthUpdateData object)
     * - [2] Market name
     */
    params: unknown[];
}

export namespace DepthUpdate {
    /** Method name. Fixed value: `depth_update`. */
    export const Method = {
        DepthUpdate: "depth_update",
    } as const;
    export type Method = (typeof Method)[keyof typeof Method];
}
