// This file was auto-generated by Fern from our API Definition.

/**
 * Order book level tuple:
 * - [0] Price level (string)
 * - [1] Available amount at the price (string)
 */
export type DepthLevel = unknown[];
