// This file was auto-generated by Fern from our API Definition.

import type * as WhitebitApi from "../index.js";

export interface DepthUpdateData {
    /** Timestamp from matchengine */
    timestamp: number;
    /** Update ID */
    update_id?: number | undefined;
    /** Previous update ID (present in incremental updates only, not in first snapshot) */
    past_update_id?: number | undefined;
    asks: WhitebitApi.DepthLevel[];
    bids: WhitebitApi.DepthLevel[];
    /** Event time */
    event_time: number;
}
