// This file was auto-generated by Fern from our API Definition.

import type * as WhitebitApi from "../index.js";

export interface DepthResponse {
    id: number;
    result: WhitebitApi.OrderBook;
    error: unknown | null;
}
