// This file was auto-generated by Fern from our API Definition.

export interface Error_ {
    code?: number | undefined;
    message?: string | undefined;
    errors?: Record<string, string[]> | undefined;
}
