// This file was auto-generated by Fern from our API Definition.

export interface FlexPlan {
    /** Flex plan identifier */
    id?: string | undefined;
    /** Currency [ticker](/glossary#ticker) */
    ticker?: string | undefined;
    /** Minimum investment amount */
    minInvestment?: string | undefined;
    /** Maximum investment amount */
    maxInvestment?: string | undefined;
    /** Maximum interest rate */
    maxRate?: string | undefined;
}
