// This file was auto-generated by Fern from our API Definition.

export interface FuturesMarket {
    /** Identifier of a ticker with delimiter to separate base/target */
    ticker_id?: string | undefined;
    /** Symbol/currency code of base pair */
    stock_currency?: string | undefined;
    /** Symbol/currency code of target pair */
    money_currency?: string | undefined;
    /** Last transacted price of base currency based on given target currency */
    last_price?: string | undefined;
    /** 24 hour trading volume in base pair volume */
    stock_volume?: string | undefined;
    /** 24 hour trading volume in target pair volume */
    money_volume?: string | undefined;
    /** Current highest bid price */
    bid?: string | undefined;
    /** Current lowest ask price */
    ask?: string | undefined;
    /** Rolling 24-hours highest transaction price */
    high?: string | undefined;
    /** Rolling 24-hours lowest transaction price */
    low?: string | undefined;
    /** What product is this? Futures, Perpetual, Options? */
    product_type?: string | undefined;
    /** The open interest in the last 24 hours in contracts */
    open_interest?: string | undefined;
    /** Underlying index price */
    index_price?: string | undefined;
    /** Name of the underlying index if any */
    index_name?: string | undefined;
    /** Underlying currency for index */
    index_currency?: string | undefined;
    /** The current funding rate, which may fluctuate due to market conditions */
    funding_rate?: string | undefined;
    /** Timestamp of the next funding rate change */
    next_funding_rate_timestamp?: string | undefined;
    /** Brackets */
    brackets?: Record<string, number> | undefined;
    /** Max Leverage */
    max_leverage?: number | undefined;
    /** Funding interval in minutes */
    funding_interval_minutes?: number | undefined;
}
