// This file was auto-generated by Fern from our API Definition.

export interface LastpriceUpdate {
    id: unknown | null;
    /** Method name. Fixed value: `lastprice_update`. */
    method: "lastprice_update";
    /**
     * Update event parameters:
     * - [0] Market name
     * - [1] Last price
     */
    params: unknown[];
}
