// This file was auto-generated by Fern from our API Definition.

export interface LastpriceSubscribe {
    /** Unique request identifier */
    id: number;
    /** Method name. Fixed value: `lastprice_subscribe`. */
    method: "lastprice_subscribe";
    params: string[];
}
