// This file was auto-generated by Fern from our API Definition.

export interface MarketUpdate {
    id: unknown | null;
    /** Method name. Fixed value: `market_update`. */
    method: "market_update";
    /**
     * Update event parameters:
     * - [0] Market name
     * - [1] MarketStatistics object
     */
    params: unknown[];
}
