// This file was auto-generated by Fern from our API Definition.

export interface MarketStatistics {
    /** Period in seconds */
    period: number;
    /** Last price */
    last: string;
    /** Open price at 'now - period' time */
    open: string;
    /** Closing price for the period */
    close: string;
    /** Highest price in the period */
    high: string;
    /** Lowest price in the period */
    low: string;
    /** Volume in [stock](/glossary#stock) currency */
    volume: string;
    /** Volume in [money](/glossary#money) currency */
    deal: string;
}
