// This file was auto-generated by Fern from our API Definition.

export interface MiningReward {
    /** Mining account name */
    miningAccountName?: string | undefined;
    /** Payout destination */
    payoutDestination?: MiningReward.PayoutDestination | undefined;
    /** Payout transaction hash. null in case payout destination is main_balance, blockchain transaction hash in case payout destination is external_address */
    payoutTransactionHash?: (string | null) | undefined;
    /** Payout address. External wallet address in case payout destination is external_address, null in case payout destination is main_balance */
    payoutAddress?: (string | null) | undefined;
    /** Timestamp when the external transaction is completed. null in case payout destination is main_balance */
    payoutTime?: (number | null) | undefined;
    /** Reward currency */
    rewardCurrency?: string | undefined;
    /** Total reward amount */
    totalReward?: string | undefined;
    /** Reward amount (without fee) */
    reward?: string | undefined;
    /** Fee amount */
    fee?: string | undefined;
    /** FPPS rate */
    fppsRate?: string | undefined;
    /** Hash rate (H/s) */
    hashRate?: string | undefined;
    /** Reward date timestamp */
    date?: number | undefined;
    /**
     * Current status of the mining reward. Possible values:
     *   - `pending` — the reward is not finalized yet. May mean either "waiting for block confirmations / batch accumulation" or "ready for payout, but the onchain transaction hasn't gone through". No user action needed — just wait.
     *   - `successful` — the reward is finalized. For `main_balance` payout, funds are credited to the main balance. For `external_address` payout, the onchain transaction is confirmed.
     *   - `canceled` — the reward was canceled.
     */
    status?: MiningReward.Status | undefined;
}

export namespace MiningReward {
    /** Payout destination */
    export const PayoutDestination = {
        MainBalance: "main_balance",
        ExternalAddress: "external_address",
    } as const;
    export type PayoutDestination = (typeof PayoutDestination)[keyof typeof PayoutDestination];
    /**
     * Current status of the mining reward. Possible values:
     *   - `pending` — the reward is not finalized yet. May mean either "waiting for block confirmations / batch accumulation" or "ready for payout, but the onchain transaction hasn't gone through". No user action needed — just wait.
     *   - `successful` — the reward is finalized. For `main_balance` payout, funds are credited to the main balance. For `external_address` payout, the onchain transaction is confirmed.
     *   - `canceled` — the reward was canceled.
     */
    export const Status = {
        Pending: "pending",
        Successful: "successful",
        Canceled: "canceled",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
