// This file was auto-generated by Fern from our API Definition.

export interface MiningReward {
    /** Mining account name */
    miningAccountName?: string | undefined;
    /** Total reward amount */
    totalReward?: string | undefined;
    /** Reward amount (without fee) */
    reward?: string | undefined;
    /** Fee amount */
    fee?: string | undefined;
    /** FPPS rate */
    fppsRate?: string | undefined;
    /** Hash rate */
    hashRate?: string | undefined;
    /** Reward date timestamp */
    date?: number | undefined;
}
