// This file was auto-generated by Fern from our API Definition.

export interface OrdersPendingUpdate {
    /** Update events have null id */
    id: unknown | null;
    /** Method name. Fixed value: `ordersPending_update`. */
    method: "ordersPending_update";
    /** Array with update event ID and order object */
    params: unknown[];
}
