// This file was auto-generated by Fern from our API Definition.

export interface OrderbookResponse {
    /** Market Name */
    ticker_id?: string | undefined;
    /** Current timestamp */
    timestamp?: number | undefined;
    /** Array of ask orders */
    asks?: string[][] | undefined;
    /** Array of bid orders */
    bids?: string[][] | undefined;
}
