// This file was auto-generated by Fern from our API Definition.

import type * as WhitebitApi from "../index.js";

export interface OrdersExecutedUpdate {
    /** Update events have null id */
    id: unknown | null;
    /** Method name. Fixed value: `ordersExecuted_update`. */
    method: OrdersExecutedUpdate.Method;
    /** Array containing executed order object */
    params: WhitebitApi.ExecutedOrderObject[];
}

export namespace OrdersExecutedUpdate {
    /** Method name. Fixed value: `ordersExecuted_update`. */
    export const Method = {
        OrdersExecutedUpdate: "ordersExecuted_update",
    } as const;
    export type Method = (typeof Method)[keyof typeof Method];
}
