// This file was auto-generated by Fern from our API Definition.

/**
 * Order object with all order details
 */
export interface OrderObject {
    /** Order ID */
    id?: number | undefined;
    /** [Market](/glossary#market) */
    market?: string | undefined;
    /** Order type. See order types table in overview */
    type?: number | undefined;
    /** Side: 1=sell, 2=buy/bid */
    side?: number | undefined;
    /** Post only flag */
    post_only?: boolean | undefined;
    /** IOC (Immediate or Cancel) flag */
    ioc?: boolean | undefined;
    /** Created at in Unix time */
    ctime?: number | undefined;
    /** Modified at in Unix time */
    mtime?: number | undefined;
    /** Order price */
    price?: string | undefined;
    /** [Stock](/glossary#stock) amount */
    amount?: string | undefined;
    /** Stock amount remaining to be executed */
    left?: string | undefined;
    /** Executed stock amount */
    deal_stock?: string | undefined;
    /** Executed [Money](/glossary#money) amount */
    deal_money?: string | undefined;
    /** Charged fee amount in money */
    deal_fee?: string | undefined;
    /** Custom client order id */
    client_order_id?: string | undefined;
    /** STP flag: no=No Prevention, co=Cancel Oldest, cn=Cancel Newest, cb=Cancel Both */
    stp?: OrderObject.Stp | undefined;
    /** Order status (e.g., OPEN, FILLED, CANCELED) */
    status?: string | undefined;
    /** Position side - LONG or SHORT or BOTH */
    position_side?: OrderObject.PositionSide | undefined;
    /** Indicates Retail Price Improvement (RPI) mode for the order. */
    rpi?: boolean | undefined;
}

export namespace OrderObject {
    /** STP flag: no=No Prevention, co=Cancel Oldest, cn=Cancel Newest, cb=Cancel Both */
    export const Stp = {
        No: "no",
        Co: "co",
        Cn: "cn",
        Cb: "cb",
    } as const;
    export type Stp = (typeof Stp)[keyof typeof Stp];
    /** Position side - LONG or SHORT or BOTH */
    export const PositionSide = {
        Long: "LONG",
        Short: "SHORT",
        Both: "BOTH",
    } as const;
    export type PositionSide = (typeof PositionSide)[keyof typeof PositionSide];
}
