// This file was auto-generated by Fern from our API Definition.

import type * as WhitebitApi from "../index.js";

export interface OrderBook {
    /** Timestamp from matchengine */
    timestamp: number;
    /** Asks sorted ascending */
    asks: WhitebitApi.DepthLevel[];
    /** Bids sorted descending */
    bids: WhitebitApi.DepthLevel[];
}
