// This file was auto-generated by Fern from our API Definition.

export interface OrdersExecutedRequest {
    /** Unique request identifier */
    id: number;
    /** Method name. Fixed value: `ordersExecuted_request`. */
    method: "ordersExecuted_request";
    /**
     * Query parameters tuple:
     * - [0] Filter object with market and order_types
     * - [1] Offset
     * - [2] Limit (max 100)
     */
    params: unknown[];
}
