// This file was auto-generated by Fern from our API Definition.

import type * as WhitebitApi from "../index.js";

export interface OrderResponse {
    /** Unique identifier assigned to the order by the matching engine. */
    orderId?: number | undefined;
    /** Custom client order identifier supplied in the request. Returns an empty string when not specified. */
    clientOrderId?: string | undefined;
    /** Trading pair for the order. Format: `BASE_QUOTE` (e.g., `BTC_USDT`). */
    market?: string | undefined;
    /** Order side. Possible values: `buy`, `sell`. */
    side?: string | undefined;
    /** Order type. Possible values: `limit`, `market`, `stock market`, `stop limit`, `stop market`. */
    type?: string | undefined;
    /** Unix timestamp in seconds (UTC) of order creation, with microsecond precision. */
    timestamp?: number | undefined;
    /** Filled amount in quote currency. Returns `"0"` while the order remains unfilled. */
    dealMoney?: string | undefined;
    /** Filled amount in base currency. Returns `"0"` while the order remains unfilled. */
    dealStock?: string | undefined;
    /** Order quantity in base currency for limit and stop-limit orders, or in quote currency for buy market orders. */
    amount?: string | undefined;
    /** Remaining unfilled quantity. Equals `amount` for new orders and `"0"` for fully filled orders. */
    left?: string | undefined;
    /** Cumulative trading fee charged for filled portions, denominated in the fee asset. */
    dealFee?: string | undefined;
    /** Limit price per unit in quote currency. Returns `"0"` for market orders. */
    price?: string | undefined;
    /** Post-only flag. When `true`, the order executes only as a maker order and is rejected if it would match immediately. Default: `false`. */
    postOnly?: boolean | undefined;
    /** Immediate-or-cancel flag. When `true`, the order executes available quantity immediately and cancels the unfilled remainder. Default: `false`. */
    ioc?: boolean | undefined;
    status?: WhitebitApi.OrderStatus | undefined;
    /** Self-trade prevention mode applied to the order. Possible values: `no`, `cb`, `cn`, `co`. The response always returns the abbreviated form, even when the request used a legacy value. Default: `no`. */
    stp?: string | undefined;
    /** Position side (for collateral orders) */
    positionSide?: string | undefined;
    /** Indicates Retail Price Improvement (RPI) mode for the order. */
    rpi?: boolean | undefined;
    /** Retail-source taker flag. The field is present only when the order was placed with `retail=true`. See [Retail flag](/glossary#retail-flag). */
    retail?: boolean | undefined;
    /** Reduce-only flag. When `true`, the order can only reduce or close an existing position. See [reduce-only](/glossary#reduce-only). */
    reduceOnly?: boolean | undefined;
    /** Activation status of the stop order. 0 = not yet triggered (waiting for the activation_price condition to be met). 1 = triggered (the stop condition has been met and the order is now active). */
    activated?: number | undefined;
    /**
     * Trigger condition for the stop order. Response-only — not accepted in the request body, and cannot be overridden. Derived from `side`:
     *
     * - `side = buy` → `gte`. The order activates when the market price rises to or above `activation_price`.
     * - `side = sell` → `lte`. The order activates when the market price falls to or below `activation_price`.
     */
    activationCondition?: OrderResponse.ActivationCondition | undefined;
    /** The trigger price for the stop order. Always equals the activation_price value submitted in the request. */
    activation_price?: string | undefined;
}

export namespace OrderResponse {
    /**
     * Trigger condition for the stop order. Response-only — not accepted in the request body, and cannot be overridden. Derived from `side`:
     *
     * - `side = buy` → `gte`. The order activates when the market price rises to or above `activation_price`.
     * - `side = sell` → `lte`. The order activates when the market price falls to or below `activation_price`.
     */
    export const ActivationCondition = {
        Lte: "lte",
        Gte: "gte",
    } as const;
    export type ActivationCondition = (typeof ActivationCondition)[keyof typeof ActivationCondition];
}
