// This file was auto-generated by Fern from our API Definition.

import type * as WhitebitApi from "../index.js";

export interface OrdersExecutedUpdate {
    /** Update events have null id */
    id: unknown | null;
    /** Method name. Fixed value: `ordersExecuted_update`. */
    method: "ordersExecuted_update";
    /** Array containing executed order object */
    params: WhitebitApi.ExecutedOrderObject[];
}
