// This file was auto-generated by Fern from our API Definition.

import type * as WhitebitApi from "../index.js";

export interface PingResponse extends WhitebitApi.BaseResponse {
    result?: PingResponse.Result | undefined;
}

export namespace PingResponse {
    export const Result = {
        Pong: "pong",
    } as const;
    export type Result = (typeof Result)[keyof typeof Result];
}
