// This file was auto-generated by Fern from our API Definition.

export interface PositionsUpdate {
    /** Update events have null id */
    id: unknown | null;
    /** Method name. Fixed value: `positionsMargin_update`. */
    method: PositionsUpdate.Method;
    params: PositionsUpdate.Params;
}

export namespace PositionsUpdate {
    /** Method name. Fixed value: `positionsMargin_update`. */
    export const Method = {
        PositionsMarginUpdate: "positionsMargin_update",
    } as const;
    export type Method = (typeof Method)[keyof typeof Method];

    export interface Params {
        /** Positions count */
        total?: number | undefined;
        records?: Params.Records.Item[] | undefined;
    }

    export namespace Params {
        export type Records = Records.Item[];

        export namespace Records {
            export interface Item {
                /** Position ID */
                id?: number | undefined;
                /** [Market](/glossary#market) name */
                market?: string | undefined;
                /** Date of position opening in Unix time */
                ctime?: number | undefined;
                /** Date of position modification (the date of the current event) in Unix time */
                mtime?: number | undefined;
                /** Position amount */
                amount?: string | undefined;
                /** Position amount in [money](/glossary#money) */
                amount_in_money?: string | undefined;
                /** Base price of position */
                base_price?: string | undefined;
                /** Unrealized PnL in **money** */
                pnl?: string | undefined;
                /** Liquidation price according to current state of position */
                liq_price?: string | undefined;
                /** Liquidation state. Possible values: null, margin_call */
                liq_stage?: (Item.LiqStage | null) | undefined;
                /** Funding to be paid on the next position stage change (order, liquidation, etc) */
                unrealized_funding?: string | undefined;
                /** Funding already disbursed */
                funding?: string | undefined;
                /** Own funds amount in open position in **money** */
                margin?: string | undefined;
                /** Free funds for trading */
                free_margin?: string | undefined;
                /** Realized PnL in **money** */
                realized_pnl?: string | undefined;
                /** Position side - LONG or SHORT or BOTH */
                position_side?: Item.PositionSide | undefined;
            }

            export namespace Item {
                /** Liquidation state. Possible values: null, margin_call */
                export const LiqStage = {
                    MarginCall: "margin_call",
                } as const;
                export type LiqStage = (typeof LiqStage)[keyof typeof LiqStage];
                /** Position side - LONG or SHORT or BOTH */
                export const PositionSide = {
                    Long: "LONG",
                    Short: "SHORT",
                    Both: "BOTH",
                } as const;
                export type PositionSide = (typeof PositionSide)[keyof typeof PositionSide];
            }
        }
    }
}
