// This file was auto-generated by Fern from our API Definition.

export interface PositionsSubscribe {
    /** Unique request identifier */
    id: number;
    /** Method name. Fixed value: `positionsMargin_subscribe`. */
    method: PositionsSubscribe.Method;
    /** Empty array for positions subscription */
    params: unknown[];
}

export namespace PositionsSubscribe {
    /** Method name. Fixed value: `positionsMargin_subscribe`. */
    export const Method = {
        PositionsMarginSubscribe: "positionsMargin_subscribe",
    } as const;
    export type Method = (typeof Method)[keyof typeof Method];
}
