// This file was auto-generated by Fern from our API Definition.

/**
 * Fee details for a specific fiat payment provider
 */
export interface ProviderFeeDetails {
    /** Provider identifier */
    ticker?: string | undefined;
    /** Human-readable provider name */
    name?: string | undefined;
    /** Whether deposits are enabled via this provider */
    is_depositable?: boolean | undefined;
    /** Whether API deposits are enabled via this provider */
    is_api_depositable?: boolean | undefined;
    /** Whether withdrawals are enabled via this provider */
    is_withdrawal?: boolean | undefined;
    /** Whether API withdrawals are enabled via this provider */
    is_api_withdrawal?: boolean | undefined;
    /** Maximum transfer amount. `"0"` means unlimited. */
    max_amount?: string | undefined;
    /** Minimum transfer amount */
    min_amount?: string | undefined;
    /** Fixed fee amount per transaction. `null` if no fixed fee applies. */
    fixed?: (string | null) | undefined;
    /** Percentage-based (flexible) fee. `null` if no flexible fee applies. */
    flex?: (ProviderFeeDetails.Flex | null) | undefined;
}

export namespace ProviderFeeDetails {
    /**
     * Percentage-based (flexible) fee. `null` if no flexible fee applies.
     */
    export interface Flex {
        /** Fee percentage (e.g., `"1.5"` means 1.5%) */
        percent?: string | undefined;
        /** Minimum fee amount regardless of percentage calculation */
        min_fee?: string | undefined;
        /** Maximum fee amount regardless of percentage calculation */
        max_fee?: string | undefined;
    }
}
