// This file was auto-generated by Fern from our API Definition.

export interface SubAccountApiKey {
    /** Sub-account identifier */
    subAccountId?: string | undefined;
    /** API key identifier */
    id?: string | undefined;
    /** API key title/name */
    title?: string | undefined;
    /** Whether the API key is enabled */
    isEnabled?: boolean | undefined;
    /** API key */
    apiKey?: string | undefined;
    /** API secret */
    apiSecret?: string | undefined;
    /** API key type (1 - info and trading, 2 - info, trading, deposit and withdraw) */
    type?: number | undefined;
    /** Last activity timestamp */
    lastActivity?: number | undefined;
    /** Whether access is restricted */
    restrictAccess?: boolean | undefined;
    /** List of allowed endpoints */
    accessEndpoints?: SubAccountApiKey.AccessEndpoints.Item[] | undefined;
}

export namespace SubAccountApiKey {
    export type AccessEndpoints = AccessEndpoints.Item[];

    export namespace AccessEndpoints {
        export interface Item {
            /** Endpoint name */
            name?: string | undefined;
            /** Endpoint title */
            title?: string | undefined;
        }
    }
}
