// This file was auto-generated by Fern from our API Definition.

export interface SubAccount {
    /** Sub-account identifier */
    id?: string | undefined;
    /** Sub-account alias/name */
    alias?: string | undefined;
    /** User identifier associated with account */
    userId?: string | undefined;
    /** Sub-account email (masked) */
    email?: string | undefined;
    /** Sub-account status */
    status?: string | undefined;
    /** Sub-account color */
    color?: string | undefined;
    /** KYC information */
    kyc?: SubAccount.Kyc | undefined;
    /** Sub-account permissions */
    permissions?: SubAccount.Permissions | undefined;
}

export namespace SubAccount {
    /**
     * KYC information
     */
    export interface Kyc {
        /** Whether KYC is shared with main account */
        shareKyc?: boolean | undefined;
        /** KYC status */
        kycStatus?: string | undefined;
    }

    /**
     * Sub-account permissions
     */
    export interface Permissions {
        /** Spot trading enabled */
        spotEnabled?: boolean | undefined;
        /** Collateral trading enabled */
        collateralEnabled?: boolean | undefined;
    }
}
