// This file was auto-generated by Fern from our API Definition.

export interface SubAccountApiKeyList {
    subAccountId?: string | undefined;
    id?: string | undefined;
    title?: string | undefined;
    isEnabled?: boolean | undefined;
    apiKey?: string | undefined;
    /** Empty for security (only shown during creation) */
    apiSecret?: string | undefined;
    type?: string | undefined;
    lastActivity?: number | undefined;
    restrictAccess?: boolean | undefined;
    accessEndpoints?: SubAccountApiKeyList.AccessEndpoints.Item[] | undefined;
}

export namespace SubAccountApiKeyList {
    export type AccessEndpoints = AccessEndpoints.Item[];

    export namespace AccessEndpoints {
        export interface Item {
            name?: string | undefined;
            title?: string | undefined;
        }
    }
}
