// This file was auto-generated by Fern from our API Definition.

export interface SubscriptionResponse {
    /** Request identifier matching the request */
    id: number;
    result: SubscriptionResponse.Result;
    /** Error object (null on success) */
    error: unknown | null;
}

export namespace SubscriptionResponse {
    export interface Result {
        /** Fixed value: `success`. */
        status: "success";
    }
}
