// This file was auto-generated by Fern from our API Definition.

export interface TradesUpdate {
    id: unknown | null;
    /** Method name. Fixed value: `trades_update`. */
    method: "trades_update";
    /**
     * Update event parameters:
     * - [0] Market name
     * - [1] Array of Trade objects
     */
    params: unknown[];
}
