// This file was auto-generated by Fern from our API Definition.

export interface TradesSubscribe {
    id: number;
    /** Method name. Fixed value: `trades_subscribe`. */
    method: "trades_subscribe";
    /** Market names (empty array to subscribe to all markets) */
    params: string[];
}
