// This file was auto-generated by Fern from our API Definition.

/**
 * Physical address for travel rule compliance
 */
export interface TravelRuleAddress {
    /** ISO 3166-1 alpha-3 country code (3 letters) */
    country: string;
    /** City name */
    city: string;
    /** Postal code (optional) */
    postCode?: string | undefined;
    /** Street address */
    addressLine1: string;
}
