// This file was auto-generated by Fern from our API Definition.

export interface ApplyCodeResponse {
    message?: string | undefined;
    ticker?: string | undefined;
    amount?: string | undefined;
    external_id?: string | undefined;
}
