// This file was auto-generated by Fern from our API Definition.

import type * as WhitebitApi from "../../../index.js";

export interface GetMyCodesResponse {
    /** Total number of codes */
    total?: number | undefined;
    data?: WhitebitApi.CodeInfo[] | undefined;
    limit?: number | undefined;
    offset?: number | undefined;
}
