// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         method: "deposit",
 *         ticker: "XLM",
 *         amount: "0.9",
 *         request: "{{request}}",
 *         nonce: "{{nonce}}"
 *     }
 *
 * @example
 *     {
 *         from: "main",
 *         to: "spot",
 *         ticker: "XLM",
 *         amount: "0.9",
 *         request: "{{request}}",
 *         nonce: "{{nonce}}"
 *     }
 */
export interface TransferBetweenBalancesRequest {
    /**
     * Transfer method.
     *
     * ⚠️ We highly recommend to use **from** and **to** fields, which provides more flexibility. This way will be deprecated in future.
     *
     * Example: **deposit** to transfer from [main](/glossary#balance-main) to [trade](/glossary#balance-spotbalance-trade) / **withdraw** to transfer from [trade](/glossary#balance-spotbalance-trade) balance to [main](/glossary#balance-main). For [collateral balances](/glossary#balance-collateral) use **collateral-deposit** to transfer from main to collateral and **collateral-withdraw** to transfer from collateral to main
     *
     * **Not required** if **from** and **to** are set.
     */
    method?: TransferBetweenBalancesRequest.Method;
    /**
     * Balance FROM which funds will move to. Acceptable values: [**main**](/glossary#balance-main), [**spot**](/glossary#balance-spotbalance-trade), [**collateral**](/glossary#balance-collateral)
     *
     * **Not required** if **method** is set.
     */
    from?: TransferBetweenBalancesRequest.From;
    /**
     * Balance TO which funds will move to. Acceptable values: [**main**](/glossary#balance-main), [**spot**](/glossary#balance-spotbalance-trade), [**collateral**](/glossary#balance-collateral)
     *
     * **Not required** if **method** is set.
     */
    to?: TransferBetweenBalancesRequest.To;
    /** Currency's [ticker](/glossary#ticker). Example: BTC */
    ticker: string;
    /** Amount to transfer. Max [precision](/glossary#precision) = 8, value must be greater than zero and less than or equal to the available balance. */
    amount: string;
    /** Request signature */
    request: string;
    /** Unique request identifier */
    nonce: string;
}

export namespace TransferBetweenBalancesRequest {
    /**
     * Transfer method.
     *
     * ⚠️ We highly recommend to use **from** and **to** fields, which provides more flexibility. This way will be deprecated in future.
     *
     * Example: **deposit** to transfer from [main](/glossary#balance-main) to [trade](/glossary#balance-spotbalance-trade) / **withdraw** to transfer from [trade](/glossary#balance-spotbalance-trade) balance to [main](/glossary#balance-main). For [collateral balances](/glossary#balance-collateral) use **collateral-deposit** to transfer from main to collateral and **collateral-withdraw** to transfer from collateral to main
     *
     * **Not required** if **from** and **to** are set.
     */
    export const Method = {
        Deposit: "deposit",
        Withdraw: "withdraw",
        CollateralDeposit: "collateral-deposit",
        CollateralWithdraw: "collateral-withdraw",
    } as const;
    export type Method = (typeof Method)[keyof typeof Method];
    /**
     * Balance FROM which funds will move to. Acceptable values: [**main**](/glossary#balance-main), [**spot**](/glossary#balance-spotbalance-trade), [**collateral**](/glossary#balance-collateral)
     *
     * **Not required** if **method** is set.
     */
    export const From = {
        Main: "main",
        Spot: "spot",
        Collateral: "collateral",
    } as const;
    export type From = (typeof From)[keyof typeof From];
    /**
     * Balance TO which funds will move to. Acceptable values: [**main**](/glossary#balance-main), [**spot**](/glossary#balance-spotbalance-trade), [**collateral**](/glossary#balance-collateral)
     *
     * **Not required** if **method** is set.
     */
    export const To = {
        Main: "main",
        Spot: "spot",
        Collateral: "collateral",
    } as const;
    export type To = (typeof To)[keyof typeof To];
}
