// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         request: "{{request}}",
 *         nonceWindow: false,
 *         nonce: "{{nonce}}"
 *     }
 */
export interface IssueJwtTokenRequest {
    /** Request signature */
    request: string;
    /** Nonce window setting */
    nonceWindow?: boolean;
    /** Unique request identifier */
    nonce: string;
}
