// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListSubAccountApiKeysRequest {
    /** ID of the sub-account to list API keys for */
    subAccountId?: string;
    limit?: number;
    offset?: number;
}
