// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         request: "{{request}}",
 *         nonce: "{{nonce}}"
 *     }
 */
export interface GetFeesRequest {
    /** Request signature */
    request: string;
    /** Unique request identifier */
    nonce: string;
}
