// This file was auto-generated by Fern from our API Definition.

export interface GetDelistingOrderHistoryResponseItem {
    /** Unique order identifier assigned by the matching engine. */
    id?: number | undefined;
    /** Custom client order identifier. Reverse close orders carry the platform-generated value prefixed with `delisting-`. Returns an empty string when the original order had no client identifier. */
    clientOrderId?: string | undefined;
    /** Unix timestamp in seconds (UTC) of order creation, with microsecond precision. */
    createdAt?: number | undefined;
    /** Unix timestamp in seconds (UTC) at which the order reached its final status, with microsecond precision. Primary sort key, descending. */
    finishAt?: number | undefined;
    /** Trading pair the order belongs to. Format: `BASE_QUOTE`. */
    market?: string | undefined;
    /** Order side. Possible values: `buy`, `sell`. */
    side?: GetDelistingOrderHistoryResponseItem.Side | undefined;
    /** Order type. Possible values: `limit`, `market`, `stock market`, `stop limit`, `stop market`. */
    type?: string | undefined;
    /** Limit price per unit in quote currency. Returns `"0"` for market orders. */
    price?: string | undefined;
    /** Order quantity in base currency for limit orders, or in quote currency for buy market orders. */
    amount?: string | undefined;
    /** Filled amount in base (stock) currency. */
    dealStock?: string | undefined;
    /** Filled amount in quote (money) currency. */
    dealMoney?: string | undefined;
    /** Cumulative trading fee charged for filled portions, denominated in the fee asset. */
    fee?: string | undefined;
    /** Currency ticker of the asset used to pay the trading fee. */
    feeAsset?: string | undefined;
    /** Execution outcome in lowercase. Reverse close orders that filled return `filled`. Orders canceled during delisting return `canceled`. */
    status?: string | undefined;
    /** Delisting category discriminator. `reverse` marks a reverse close order generated by the platform. `canceled` marks an active order canceled at the moment of delisting. */
    delistingKind?: GetDelistingOrderHistoryResponseItem.DelistingKind | undefined;
}

export namespace GetDelistingOrderHistoryResponseItem {
    /** Order side. Possible values: `buy`, `sell`. */
    export const Side = {
        Buy: "buy",
        Sell: "sell",
    } as const;
    export type Side = (typeof Side)[keyof typeof Side];
    /** Delisting category discriminator. `reverse` marks a reverse close order generated by the platform. `canceled` marks an active order canceled at the moment of delisting. */
    export const DelistingKind = {
        Reverse: "reverse",
        Canceled: "canceled",
    } as const;
    export type DelistingKind = (typeof DelistingKind)[keyof typeof DelistingKind];
}
