// This file was auto-generated by Fern from our API Definition.

export interface GetExecutedOrderHistoryResponseItem {
    /** Deal ID */
    id?: number | undefined;
    /** Custom order ID (empty if not specified) */
    client_order_id?: string | undefined;
    /** Timestamp of executed deal */
    time?: number | undefined;
    side?: GetExecutedOrderHistoryResponseItem.Side | undefined;
    /** 1 - maker, 2 - taker */
    role?: number | undefined;
    /** Amount in stock currency */
    amount?: string | undefined;
    price?: string | undefined;
    /** Amount in money currency */
    deal?: string | undefined;
    /** Paid fee */
    fee?: string | undefined;
    order_id?: number | undefined;
    feeAsset?: string | undefined;
}

export namespace GetExecutedOrderHistoryResponseItem {
    export const Side = {
        Buy: "buy",
        Sell: "sell",
    } as const;
    export type Side = (typeof Side)[keyof typeof Side];
}
