// This file was auto-generated by Fern from our API Definition.

export interface GetOrderDealsResponse {
    /** Array of deal records */
    records?: GetOrderDealsResponse.Records.Item[] | undefined;
    /** Number of records skipped */
    offset?: number | undefined;
    /** Number of records per page */
    limit?: number | undefined;
}

export namespace GetOrderDealsResponse {
    export type Records = Records.Item[];

    export namespace Records {
        export interface Item {
            /** Timestamp of executed order */
            time?: number | undefined;
            /** Fee paid */
            fee?: string | undefined;
            /** Deal price */
            price?: string | undefined;
            /** Amount in stock */
            amount?: string | undefined;
            /** Deal identifier */
            id?: number | undefined;
            /** Completed order identifier */
            dealOrderId?: number | undefined;
            /** Custom order identifier. Empty string if not specified */
            client_order_id?: string | undefined;
            /** Role in the deal (1 - maker, 2 - taker) */
            role?: number | undefined;
            /** Amount in money */
            deal?: string | undefined;
            /** Fee asset */
            feeAsset?: string | undefined;
            /** Retail Price Improvement flag */
            rpi?: boolean | undefined;
        }
    }
}
