// This file was auto-generated by Fern from our API Definition.

import type * as WhitebitApi from "../../../index.js";

export interface GetOrderHistoryResponseValueItem {
    /** Order quantity in base currency for limit orders, or in quote currency for buy market orders. */
    amount?: string | undefined;
    /** Limit price per unit in quote currency. Returns `"0"` for market orders. */
    price?: string | undefined;
    /** Order type. Possible values: `limit`, `market`, `stock market`, `stop limit`, `stop market`. */
    type?: string | undefined;
    /** Unique order identifier assigned by the matching engine. */
    id?: number | undefined;
    /** Custom client order identifier supplied in the request. Returns an empty string when not specified. */
    clientOrderId?: string | undefined;
    /** Order side. Possible values: `buy`, `sell`. */
    side?: GetOrderHistoryResponseValueItem.Side | undefined;
    /** Unix timestamp in seconds (UTC) of order creation, with microsecond precision. */
    ctime?: number | undefined;
    /** Unix timestamp when the order reached its final status (FILLED or CANCELLED). For partially-filled orders that are subsequently cancelled, the timestamp reflects the cancellation time, not the last fill time. */
    ftime?: number | undefined;
    /** Cumulative trading fee charged for filled portions, denominated in the fee asset. */
    dealFee?: string | undefined;
    /** Filled amount in base (stock) currency. */
    dealStock?: string | undefined;
    /** Filled amount in quote (money) currency. */
    dealMoney?: string | undefined;
    /** Post-only flag. When `true`, the order executed only as a maker order. */
    postOnly?: boolean | undefined;
    /** Immediate-or-cancel flag. When `true`, the order executed available quantity immediately and cancelled the rest. */
    ioc?: boolean | undefined;
    /** Stop/conditional orders only — Unix timestamp at which the trigger price was reached and the order was activated. Absent for unconditional orders. */
    activated?: number | undefined;
    /** Stop/conditional orders only — the trigger price that, when reached, activates the order. Absent for unconditional orders. */
    activationPrice?: string | undefined;
    /** Stop/conditional orders only — comparison operator that decides when `activationPrice` is met. Absent for unconditional orders. */
    activationCondition?: string | undefined;
    status?: WhitebitApi.OrderStatus | undefined;
    /** Currency ticker of the asset used to pay the trading fee. */
    feeAsset?: string | undefined;
    /** Position side for futures/margin orders. Omitted for spot orders without position context. */
    positionSide?: string | undefined;
    /** Retail Price Improvement flag. `true` when the order used RPI pricing. */
    rpi?: boolean | undefined;
    /** Reduce-only flag. When `true`, the order could only reduce or close an existing position. See [reduce-only](/glossary#reduce-only). */
    reduceOnly?: boolean | undefined;
}

export namespace GetOrderHistoryResponseValueItem {
    /** Order side. Possible values: `buy`, `sell`. */
    export const Side = {
        Buy: "buy",
        Sell: "sell",
    } as const;
    export type Side = (typeof Side)[keyof typeof Side];
}
