// This file was auto-generated by Fern from our API Definition.

export interface SetKillSwitchResponse {
    /** Trading pair the timer applies to. */
    market?: string | undefined;
    /** Unix timestamp (seconds) when the timer was created or last reset. */
    startTime?: number | undefined;
    /** Unix timestamp (seconds) when the kill-switch will cancel orders. Equals `startTime + timeout`. */
    cancellationTime?: number | undefined;
    /** Order types targeted by the kill-switch. Possible values: `spot`, `margin`, `futures`. */
    types?: SetKillSwitchResponse.Types.Item[] | undefined;
}

export namespace SetKillSwitchResponse {
    export type Types = Types.Item[];

    export namespace Types {
        export const Item = {
            Spot: "spot",
            Margin: "margin",
            Futures: "futures",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
