// This file was auto-generated by Fern from our API Definition.

export interface SetKillSwitchResponse {
    /** Market name */
    market?: string | undefined;
    /** Timer start timestamp */
    startTime?: number | undefined;
    /** Order cancellation timestamp (startTime + timeout) */
    cancellationTime?: number | undefined;
    /** Order types affected by kill-switch */
    types?: SetKillSwitchResponse.Types.Item[] | undefined;
}

export namespace SetKillSwitchResponse {
    export type Types = Types.Item[];

    export namespace Types {
        export const Item = {
            Spot: "spot",
            Margin: "margin",
            Futures: "futures",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
