// This file was auto-generated by Fern from our API Definition.

import type * as WhitebitApi from "../../../../index.js";

/**
 * @example
 *     {
 *         market: "BTC_USDT"
 *     }
 */
export interface GetApiV4PublicTradesMarketRequest {
    /** Market pair name */
    market: string;
    /** Filter by trade side. Omit to return both buy and sell trades. */
    type?: WhitebitApi.GetApiV4PublicTradesMarketRequestType;
}
