// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         market: "BTC_PERP",
 *         startDate: 1752480000,
 *         endDate: 1752537600,
 *         limit: 100,
 *         offset: 0
 *     }
 */
export interface GetApiV4PublicFundingHistoryMarketRequest {
    /** Market name (e.g., BTC_PERP) */
    market: string;
    /** Start timestamp in seconds */
    startDate?: number;
    /** End timestamp in seconds */
    endDate?: number;
    /** Number of records to return. Default: 100, Maximum: 100 */
    limit?: number;
    /** Number of records to skip. Maximum: 1000000 */
    offset?: number;
}
