// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         market: "BTC_USDT"
 *     }
 */
export interface GetApiV4PublicOrderbookDepthMarketRequest {
    /** Market pair name */
    market: string;
}
