// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         alias: "trading_bot",
 *         permissions: {
 *             spotEnabled: true,
 *             collateralEnabled: false
 *         }
 *     }
 */
export interface CreateSubAccountRequest {
    /** Name for sub-account */
    alias: string;
    /** Sub-account email (required when shareKyc is false) */
    email?: string;
    /** If KYC shared with main account */
    shareKyc?: boolean;
    permissions: CreateSubAccountRequest.Permissions;
}

export namespace CreateSubAccountRequest {
    export interface Permissions {
        /** Enable transfers to trade balance */
        spotEnabled: boolean;
        /** Enable transfers to collateral balance */
        collateralEnabled: boolean;
    }
}
