// This file was auto-generated by Fern from our API Definition.

export interface GetTravelRuleVaspsResponse {
    data?: GetTravelRuleVaspsResponse.Data | undefined;
}

export namespace GetTravelRuleVaspsResponse {
    export interface Data {
        vasps?: Data.Vasps.Item[] | undefined;
    }

    export namespace Data {
        export type Vasps = Vasps.Item[];

        export namespace Vasps {
            export interface Item {
                /** Unique VASP identifier to use in travel rule submissions */
                vaspId?: string | undefined;
                /** Human-readable VASP name */
                name?: string | undefined;
            }
        }
    }
}
