// This file was auto-generated by Fern from our API Definition.

export interface SubmitTravelRuleDepositVerificationResponse {
    data?: SubmitTravelRuleDepositVerificationResponse.Data | undefined;
}

export namespace SubmitTravelRuleDepositVerificationResponse {
    export interface Data {
        /** Transaction external ID */
        uniqueId?: string | undefined;
        /**
         * Verification status:
         * - `submitted` - Data submitted successfully, awaiting review
         * - `approved` - Immediately approved (rare)
         * - Other SumSub review statuses
         */
        status?: string | undefined;
    }
}
