// This file was auto-generated by Fern from our API Definition.

import type * as WhitebitApi from "../../../index.js";

export interface GetApiV4PublicFuturesResponse {
    success?: boolean | undefined;
    message?: (string | null) | undefined;
    result?: WhitebitApi.FuturesMarket[] | undefined;
}
