// This file was auto-generated by Fern from our API Definition.

export interface GetApiV4PublicPlatformStatusResponse {
    /** system operational or system maintenance */
    status: GetApiV4PublicPlatformStatusResponse.Status;
}

export namespace GetApiV4PublicPlatformStatusResponse {
    /** system operational or system maintenance */
    export const Status = {
        SystemOperational: "system operational",
        SystemMaintenance: "system maintenance",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
