// This file was auto-generated by Fern from our API Definition.

export const GetApiV4PublicTradesMarketRequestType = {
    Buy: "buy",
    Sell: "sell",
} as const;
export type GetApiV4PublicTradesMarketRequestType =
    (typeof GetApiV4PublicTradesMarketRequestType)[keyof typeof GetApiV4PublicTradesMarketRequestType];
