// This file was auto-generated by Fern from our API Definition.

export interface GetApiV4PublicCollateralMarketsResponse {
    success?: boolean | undefined;
    message?: (string | null) | undefined;
    result?: string[] | undefined;
}
