// This file was auto-generated by Fern from our API Definition.

export interface GetApiV4PublicTradesMarketResponseItem {
    /** A unique ID associated with the trade for the currency pair transaction Note: Unix timestamp does not qualify as trade_id. */
    tradeID: number;
    /** Transaction price in quote pair volume. */
    price: string;
    /** Transaction amount in quote pair volume. */
    quote_volume: string;
    /** Transaction amount in base pair volume. */
    base_volume: string;
    /** Unix timestamp in milliseconds, identifies when the transaction occurred. */
    trade_timestamp: number;
    /** Used to determine whether or not the transaction originated as a buy or sell. Buy – Identifies an ask that was removed from the order book. Sell – Identifies a bid that was removed from the order book. */
    type: GetApiV4PublicTradesMarketResponseItem.Type;
    /** Indicates that the trade originates from a Retail Price Improvement (RPI) order. */
    rpi?: boolean | undefined;
}

export namespace GetApiV4PublicTradesMarketResponseItem {
    /** Used to determine whether or not the transaction originated as a buy or sell. Buy – Identifies an ask that was removed from the order book. Sell – Identifies a bid that was removed from the order book. */
    export const Type = {
        Buy: "buy",
        Sell: "sell",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
