// This file was auto-generated by Fern from our API Definition.

export interface GetApiV4PublicFundingHistoryMarketResponseItem {
    /** Unix timestamp in seconds when the funding settlement executed. */
    fundingTime: string;
    /** Funding rate applied at the settlement interval. Each record represents a historical settlement event. */
    fundingRate: string;
    /** Futures market pair name (e.g., `BTC_PERP`). */
    market: string;
    /** Mark price in the quote currency at the time of funding settlement. */
    settlementPrice: string;
    /** Unix timestamp in seconds when the funding rate was calculated. The rate is computed before the actual settlement. */
    rateCalculatedTime: string;
}
