// This file was auto-generated by Fern from our API Definition.

export interface GetApiV4PublicMiningPoolResponse {
    data?: GetApiV4PublicMiningPoolResponse.Data | undefined;
}

export namespace GetApiV4PublicMiningPoolResponse {
    export interface Data {
        connection_links?: string[] | undefined;
        location?: string | undefined;
        assets?: string[] | undefined;
        reward_schemes?: string[] | undefined;
        workers?: number | undefined;
        current_hash_rate?: string | undefined;
        last7days_hash_rate?: Data.Last7DaysHashRate.Item[] | undefined;
        blocks?: Data.Blocks.Item[] | undefined;
    }

    export namespace Data {
        export type Last7DaysHashRate = Last7DaysHashRate.Item[];

        export namespace Last7DaysHashRate {
            export interface Item {
                timestamp?: number | undefined;
                hashrate?: string | undefined;
            }
        }

        export type Blocks = Blocks.Item[];

        export namespace Blocks {
            export interface Item {
                block_found_at?: number | undefined;
                block_height?: number | undefined;
            }
        }
    }
}
