// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         quoteId: "4050"
 *     }
 */
export interface ConvertConfirmRequest {
    /** Quote ID */
    quoteId: string;
    /** Nonce for request */
    nonce?: number;
    /** Request path */
    request?: string;
}
