// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         from: "BTC",
 *         to: "USDT",
 *         direction: "to",
 *         amount: "35,103.1"
 *     }
 *
 * @example
 *     {
 *         from: "BTC",
 *         to: "USDT",
 *         direction: "from",
 *         amount: "1"
 *     }
 */
export interface ConvertEstimateRequest {
    /** From currency. Example: BTC */
    from: string;
    /** To currency. Example: USDT */
    to: string;
    /** Convert amount direction, defines in which currency corresponding "amount" field is populated. Use "to" in case amount is in "to" currency, use "from" if amount is in "from" currency */
    direction: ConvertEstimateRequest.Direction;
    /** Amount to convert or receive. */
    amount: string;
    /** Nonce for request */
    nonce?: number;
    /** Request path */
    request?: string;
}

export namespace ConvertEstimateRequest {
    /** Convert amount direction, defines in which currency corresponding "amount" field is populated. Use "to" in case amount is in "to" currency, use "from" if amount is in "from" currency */
    export const Direction = {
        From: "from",
        To: "to",
    } as const;
    export type Direction = (typeof Direction)[keyof typeof Direction];
}
