// This file was auto-generated by Fern from our API Definition.

export interface CancelOcoOrderResponse {
    /** OCO order identifier */
    id?: number | undefined;
    /** Cancelled stop loss order details */
    stop_loss?: CancelOcoOrderResponse.StopLoss | undefined;
    /** Cancelled take profit order details */
    take_profit?: CancelOcoOrderResponse.TakeProfit | undefined;
}

export namespace CancelOcoOrderResponse {
    /**
     * Cancelled stop loss order details
     */
    export interface StopLoss {
        /** Order identifier */
        order_id?: number | undefined;
        /** Custom order identifier. Empty string if not specified */
        client_order_id?: string | undefined;
        /** Market name */
        market?: string | undefined;
        /** Order side */
        side?: StopLoss.Side | undefined;
        /** Order type */
        type?: string | undefined;
        /** Timestamp of order creation */
        timestamp?: number | undefined;
        /** Executed amount in money */
        deal_money?: string | undefined;
        /** Executed amount in stock */
        deal_stock?: string | undefined;
        /** Order amount */
        amount?: string | undefined;
        /** Taker fee ratio */
        takerFee?: string | undefined;
        /** Maker fee ratio */
        makerFee?: string | undefined;
        /** Unexecuted amount in stock */
        left?: string | undefined;
        /** Executed fee by deal */
        deal_fee?: string | undefined;
        /** Post-only flag */
        post_only?: boolean | undefined;
        /** Timestamp of order modification */
        mtime?: number | undefined;
        /** Order price */
        price?: string | undefined;
        /** Activation price */
        activation_price?: string | undefined;
        /** Activation condition */
        activation_condition?: StopLoss.ActivationCondition | undefined;
        /** Activation status (0 - not activated, 1 - activated) */
        activated?: number | undefined;
        /** Order status */
        status?: string | undefined;
        /** Self trade prevention mode */
        stp?: string | undefined;
    }

    export namespace StopLoss {
        /** Order side */
        export const Side = {
            Buy: "buy",
            Sell: "sell",
        } as const;
        export type Side = (typeof Side)[keyof typeof Side];
        /** Activation condition */
        export const ActivationCondition = {
            Gte: "gte",
            Lte: "lte",
        } as const;
        export type ActivationCondition = (typeof ActivationCondition)[keyof typeof ActivationCondition];
    }

    /**
     * Cancelled take profit order details
     */
    export interface TakeProfit {
        /** Order identifier */
        order_id?: number | undefined;
        /** Custom order identifier. Empty string if not specified */
        client_order_id?: string | undefined;
        /** Market name */
        market?: string | undefined;
        /** Order side */
        side?: TakeProfit.Side | undefined;
        /** Order type */
        type?: string | undefined;
        /** Timestamp of order creation */
        timestamp?: number | undefined;
        /** Executed amount in money */
        deal_money?: string | undefined;
        /** Executed amount in stock */
        deal_stock?: string | undefined;
        /** Order amount */
        amount?: string | undefined;
        /** Unexecuted amount in stock */
        left?: string | undefined;
        /** Executed fee by deal */
        deal_fee?: string | undefined;
        /** Post-only flag */
        post_only?: boolean | undefined;
        /** Timestamp of order modification */
        mtime?: number | undefined;
        /** Order price */
        price?: string | undefined;
        /** Order status */
        status?: string | undefined;
        /** Self trade prevention mode */
        stp?: string | undefined;
    }

    export namespace TakeProfit {
        /** Order side */
        export const Side = {
            Buy: "buy",
            Sell: "sell",
        } as const;
        export type Side = (typeof Side)[keyof typeof Side];
    }
}
