// This file was auto-generated by Fern from our API Definition.

import type * as WhitebitApi from "../../../index.js";

export interface CreateCollateralTriggerMarketOrderResponse {
    /** Unique order identifier */
    orderId?: number | undefined;
    /** Custom client order identifier. Empty string if not specified */
    clientOrderId?: string | undefined;
    /** Market name */
    market?: string | undefined;
    /** Order side */
    side?: CreateCollateralTriggerMarketOrderResponse.Side | undefined;
    /** Order type */
    type?: string | undefined;
    /** Unix timestamp in seconds (UTC) of order creation, with microsecond precision. */
    timestamp?: number | undefined;
    /** Amount in money currency that is finished */
    dealMoney?: string | undefined;
    /** Amount in stock currency that is finished */
    dealStock?: string | undefined;
    /** Order amount */
    amount?: string | undefined;
    /** Remaining amount that must be finished */
    left?: string | undefined;
    /** Fee in money that is paid when order is finished */
    dealFee?: string | undefined;
    /** Price at which the stop market order activates */
    activation_price?: string | undefined;
    status?: WhitebitApi.ActiveOrderStatus | undefined;
    /** Self-trade prevention mode. Possible values: `no`, `cb`, `cn`, `co`. Always returned in abbreviated form, even when the request used a legacy value. */
    stp?: string | undefined;
    /** OTO order data when stopLoss or takeProfit is specified */
    oto?: (CreateCollateralTriggerMarketOrderResponse.Oto | null) | undefined;
    /** Position side */
    positionSide?: CreateCollateralTriggerMarketOrderResponse.PositionSide | undefined;
    /** Reduce-only flag */
    reduceOnly?: boolean | undefined;
}

export namespace CreateCollateralTriggerMarketOrderResponse {
    /** Order side */
    export const Side = {
        Buy: "buy",
        Sell: "sell",
    } as const;
    export type Side = (typeof Side)[keyof typeof Side];

    /**
     * OTO order data when stopLoss or takeProfit is specified
     */
    export interface Oto {
        /** OTO order identifier */
        otoId?: number | undefined;
        /** Stop loss order price */
        stopLoss?: string | undefined;
        /** Take profit order price */
        takeProfit?: string | undefined;
    }

    /** Position side */
    export const PositionSide = {
        Long: "LONG",
        Short: "SHORT",
        Both: "BOTH",
    } as const;
    export type PositionSide = (typeof PositionSide)[keyof typeof PositionSide];
}
