// This file was auto-generated by Fern from our API Definition.

import type * as WhitebitApi from "../../../index.js";

export interface CreateCollateralBulkOrderResponseItem {
    /** Order data when successful, null when failed */
    result?: (CreateCollateralBulkOrderResponseItem.Result | null) | undefined;
    /** Error details when order creation failed, null when successful */
    error?: (CreateCollateralBulkOrderResponseItem.Error_ | null) | undefined;
}

export namespace CreateCollateralBulkOrderResponseItem {
    /**
     * Order data when successful, null when failed
     */
    export interface Result {
        /** Unique order identifier */
        orderId?: number | undefined;
        /** Custom client order identifier. Empty string if not specified */
        clientOrderId?: string | undefined;
        /** Market name */
        market?: string | undefined;
        /** Order side */
        side?: Result.Side | undefined;
        /** Order type */
        type?: string | undefined;
        /** Unix timestamp in seconds (UTC) of order creation, with microsecond precision. */
        timestamp?: number | undefined;
        /** Amount in money currency that is finished */
        dealMoney?: string | undefined;
        /** Amount in stock currency that is finished */
        dealStock?: string | undefined;
        /** Order amount */
        amount?: string | undefined;
        /** Remaining amount that must be finished */
        left?: string | undefined;
        /** Fee in money that is paid when order is finished */
        dealFee?: string | undefined;
        /** Order price */
        price?: string | undefined;
        /** Post-only flag */
        postOnly?: boolean | undefined;
        /** Immediate or cancel flag */
        ioc?: boolean | undefined;
        status?: WhitebitApi.ActiveOrderStatus | undefined;
        /** Self-trade prevention mode. Possible values: `no`, `cb`, `cn`, `co`. Always returned in abbreviated form, even when the request used a legacy value. */
        stp?: string | undefined;
        /** Position side */
        positionSide?: Result.PositionSide | undefined;
        /** Retail Price Improvement flag */
        rpi?: boolean | undefined;
        /** Reduce-only flag */
        reduceOnly?: boolean | undefined;
    }

    export namespace Result {
        /** Order side */
        export const Side = {
            Buy: "buy",
            Sell: "sell",
        } as const;
        export type Side = (typeof Side)[keyof typeof Side];
        /** Position side */
        export const PositionSide = {
            Long: "LONG",
            Short: "SHORT",
            Both: "BOTH",
        } as const;
        export type PositionSide = (typeof PositionSide)[keyof typeof PositionSide];
    }

    /**
     * Error details when order creation failed, null when successful
     */
    export interface Error_ {
        /** Error code */
        code?: number | undefined;
        /** Error message */
        message?: string | undefined;
        /** Detailed validation errors */
        errors?: Record<string, string[]> | undefined;
    }
}
