// This file was auto-generated by Fern from our API Definition.

import type * as WhitebitApi from "../../../index.js";

export type GetConditionalOrdersResponseRecordsItem =
    /**
     * OCO type conditional order */
    | WhitebitApi.GetConditionalOrdersResponseRecordsItem.Oco
    /**
     * OTO type conditional order */
    | WhitebitApi.GetConditionalOrdersResponseRecordsItem.Oto;

export namespace GetConditionalOrdersResponseRecordsItem {
    export interface Oco {
        type: "oco";
        /** Conditional order identifier */
        id?: number | undefined;
        /** Conditional order subtype. Omitted when not set. */
        conditionalOrderType?: string | undefined;
        /** Stop-loss leg of the OCO order. The `reduceOnly` flag is returned per leg. */
        stopLoss?: WhitebitApi.ConditionalOrderLeg | undefined;
        /** Take-profit leg of the OCO order. The `reduceOnly` flag is returned per leg. */
        takeProfit?: WhitebitApi.ConditionalOrderLeg | undefined;
    }

    export interface Oto {
        type: "oto";
        /** Conditional order identifier */
        id?: number | undefined;
        /** Conditional order subtype. Omitted when not set. */
        conditionalOrderType?: string | undefined;
        /** Stop loss order price */
        stopLossPrice?: string | undefined;
        /** Take profit order price */
        takeProfitPrice?: string | undefined;
        /** The linked active order. Same shape as an `/api/v4/orders` record, including its per-order `reduceOnly` flag. */
        conditionalOrder?: WhitebitApi.OrderResponse | undefined;
    }
}
