// This file was auto-generated by Fern from our API Definition.

export interface GetClosedPositionsPnlResponseItem {
    /** Unique identifier of the closed position. */
    positionId?: number | undefined;
    /** Market of the position. Format: `BASE_QUOTE`. */
    market?: string | undefined;
    /** Realized profit and loss of the position before funding. Trading fees are already deducted from the value; `totalTradeFee` is informational and must not be subtracted again. */
    grossPnl?: string | undefined;
    /** Net profit and loss of the position: `grossPnl` minus `totalFunding`. */
    netPnl?: string | undefined;
    /** Sum of trading fees across all fills of the position, both opening and closing. Informational — already reflected in `grossPnl` and `netPnl`. */
    totalTradeFee?: string | undefined;
    /** Cumulative funding fee over the whole position lifetime. */
    totalFunding?: string | undefined;
    /** Volume-weighted average price of the fills that increased the position, trimmed to the market money precision. */
    avgEntryPrice?: string | undefined;
    /** Volume-weighted average price of the fills that reduced the position, trimmed to the market money precision. */
    avgExitPrice?: string | undefined;
    /** Total closed volume in base currency — the sum of fills that reduced the position. */
    closedSize?: string | undefined;
    /** Remaining position size. Always returns `"0"` — a closed position holds no size. */
    amount?: string | undefined;
    /** Position direction. Returns `BOTH` for positions opened with hedge mode disabled. See [positionSide](/glossary#position-side). */
    side?: GetClosedPositionsPnlResponseItem.Side | undefined;
    /** Whether the position was opened in [hedge mode](/glossary#hedge-mode). */
    isHedge?: boolean | undefined;
    /** Position open time as a Unix timestamp in seconds. */
    openDate?: number | undefined;
    /** Position close time as a Unix timestamp in seconds. Primary sort key, descending. */
    closeDate?: number | undefined;
}

export namespace GetClosedPositionsPnlResponseItem {
    /** Position direction. Returns `BOTH` for positions opened with hedge mode disabled. See [positionSide](/glossary#position-side). */
    export const Side = {
        Long: "LONG",
        Short: "SHORT",
        Both: "BOTH",
    } as const;
    export type Side = (typeof Side)[keyof typeof Side];
}
