// This file was auto-generated by Fern from our API Definition.

import type * as WhitebitApi from "../../../index.js";

export type GetConditionalOrdersResponseRecordsItem =
    /**
     * OCO type conditional order */
    | WhitebitApi.GetConditionalOrdersResponseRecordsItem.Oco
    /**
     * OTO type conditional order */
    | WhitebitApi.GetConditionalOrdersResponseRecordsItem.Oto;

export namespace GetConditionalOrdersResponseRecordsItem {
    export interface Oco {
        type: "oco";
        id?: number | undefined;
        stop_loss?: GetConditionalOrdersResponseRecordsItemOco.StopLoss | undefined;
        take_profit?: GetConditionalOrdersResponseRecordsItemOco.TakeProfit | undefined;
    }

    export namespace GetConditionalOrdersResponseRecordsItemOco {
        export interface StopLoss {
            order_id?: number | undefined;
            positionSide?: StopLoss.PositionSide | undefined;
        }

        export namespace StopLoss {
            export const PositionSide = {
                Long: "LONG",
                Short: "SHORT",
                Both: "BOTH",
            } as const;
            export type PositionSide = (typeof PositionSide)[keyof typeof PositionSide];
        }

        export interface TakeProfit {
            order_id?: number | undefined;
            positionSide?: TakeProfit.PositionSide | undefined;
        }

        export namespace TakeProfit {
            export const PositionSide = {
                Long: "LONG",
                Short: "SHORT",
                Both: "BOTH",
            } as const;
            export type PositionSide = (typeof PositionSide)[keyof typeof PositionSide];
        }
    }

    export interface Oto {
        type: "oto";
        id?: number | undefined;
        stopLossPrice?: string | undefined;
        takeProfitPrice?: string | undefined;
        conditionalOrder?: GetConditionalOrdersResponseRecordsItemOto.ConditionalOrder | undefined;
    }

    export namespace GetConditionalOrdersResponseRecordsItemOto {
        export interface ConditionalOrder {
            order_id?: number | undefined;
            client_order_id?: string | undefined;
            market?: string | undefined;
            positionSide?: ConditionalOrder.PositionSide | undefined;
        }

        export namespace ConditionalOrder {
            export const PositionSide = {
                Long: "LONG",
                Short: "SHORT",
                Both: "BOTH",
            } as const;
            export type PositionSide = (typeof PositionSide)[keyof typeof PositionSide];
        }
    }
}
