// This file was auto-generated by Fern from our API Definition.

import type * as WhitebitApi from "../../../index.js";

export interface GetConditionalOrdersResponse {
    /** Number of records per page */
    limit?: number | undefined;
    /** Number of records skipped */
    offset?: number | undefined;
    /** Total number of records */
    total?: number | undefined;
    /** Array of conditional orders (can be OCO or OTO type) */
    records?: WhitebitApi.GetConditionalOrdersResponseRecordsItem[] | undefined;
}
