// This file was auto-generated by Fern from our API Definition.

export interface GetOcoOrdersResponseItem {
    /** OCO order identifier */
    id?: number | undefined;
    /** Stop loss order details */
    stop_loss?: GetOcoOrdersResponseItem.StopLoss | undefined;
    /** Take profit order details */
    take_profit?: GetOcoOrdersResponseItem.TakeProfit | undefined;
}

export namespace GetOcoOrdersResponseItem {
    /**
     * Stop loss order details
     */
    export interface StopLoss {
        orderId?: number | undefined;
        clientOrderId?: string | undefined;
        market?: string | undefined;
        side?: StopLoss.Side | undefined;
        type?: string | undefined;
        timestamp?: number | undefined;
        dealMoney?: string | undefined;
        dealStock?: string | undefined;
        amount?: string | undefined;
        takerFee?: string | undefined;
        makerFee?: string | undefined;
        left?: string | undefined;
        dealFee?: string | undefined;
        post_only?: boolean | undefined;
        mtime?: number | undefined;
        price?: string | undefined;
        activation_price?: string | undefined;
        /** Trigger condition derived from `side` (response-only, cannot be overridden): `buy` → `gte`, `sell` → `lte`. */
        activation_condition?: StopLoss.ActivationCondition | undefined;
        activated?: number | undefined;
        status?: string | undefined;
        stp?: string | undefined;
    }

    export namespace StopLoss {
        export const Side = {
            Buy: "buy",
            Sell: "sell",
        } as const;
        export type Side = (typeof Side)[keyof typeof Side];
        /** Trigger condition derived from `side` (response-only, cannot be overridden): `buy` → `gte`, `sell` → `lte`. */
        export const ActivationCondition = {
            Gte: "gte",
            Lte: "lte",
        } as const;
        export type ActivationCondition = (typeof ActivationCondition)[keyof typeof ActivationCondition];
    }

    /**
     * Take profit order details
     */
    export interface TakeProfit {
        orderId?: number | undefined;
        clientOrderId?: string | undefined;
        market?: string | undefined;
        side?: TakeProfit.Side | undefined;
        type?: string | undefined;
        timestamp?: number | undefined;
        dealMoney?: string | undefined;
        dealStock?: string | undefined;
        amount?: string | undefined;
        takerFee?: string | undefined;
        makerFee?: string | undefined;
        left?: string | undefined;
        dealFee?: string | undefined;
        post_only?: boolean | undefined;
        mtime?: number | undefined;
        price?: string | undefined;
        status?: string | undefined;
        stp?: string | undefined;
    }

    export namespace TakeProfit {
        export const Side = {
            Buy: "buy",
            Sell: "sell",
        } as const;
        export type Side = (typeof Side)[keyof typeof Side];
    }
}
