// This file was auto-generated by Fern from our API Definition.

export interface GetPositionsHistoryResponseItem {
    /** Position identifier */
    positionId?: number | undefined;
    /** Position market */
    market?: string | undefined;
    /** Date of position opening in Unix timestamp format */
    openDate?: number | undefined;
    /** Date of position modification (current event) in Unix timestamp format */
    modifyDate?: number | undefined;
    /** Position amount */
    amount?: string | undefined;
    /** Base price of position */
    basePrice?: string | undefined;
    /** Funding fee for whole position lifetime till current state */
    realizedFunding?: string | undefined;
    /** Liquidation price according to current state of position */
    liquidationPrice?: (string | null) | undefined;
    /** State of liquidation */
    liquidationState?: (GetPositionsHistoryResponseItem.LiquidationState | null) | undefined;
    /** Details of order which changes position */
    orderDetail?: GetPositionsHistoryResponseItem.OrderDetail | undefined;
    /** Position direction. `BOTH` indicates a one-way mode position; `LONG` or `SHORT` indicates a hedge mode position. See [position side](/glossary#position-side). */
    side?: GetPositionsHistoryResponseItem.Side | undefined;
    /** Indicates whether [hedge mode](/glossary#hedge-mode) was active when the position was opened. Hedge-mode toggling requires zero open positions, so the value also reflects the account mode at every event in the position's lifetime. */
    isHedge?: boolean | undefined;
}

export namespace GetPositionsHistoryResponseItem {
    /** State of liquidation */
    export const LiquidationState = {
        MarginCall: "margin_call",
        Liquidation: "liquidation",
    } as const;
    export type LiquidationState = (typeof LiquidationState)[keyof typeof LiquidationState];

    /**
     * Details of order which changes position
     */
    export interface OrderDetail {
        /** Order identifier */
        id?: number | undefined;
        /** Trade amount of order */
        tradeAmount?: string | undefined;
        /** Order price */
        price?: string | undefined;
        /** Order trade fee */
        tradeFee?: string | undefined;
        /** Funding fee captured by this position change */
        fundingFee?: (string | null) | undefined;
        /** Realized profit and loss */
        realizedPnl?: (string | null) | undefined;
    }

    /** Position direction. `BOTH` indicates a one-way mode position; `LONG` or `SHORT` indicates a hedge mode position. See [position side](/glossary#position-side). */
    export const Side = {
        Long: "LONG",
        Short: "SHORT",
        Both: "BOTH",
    } as const;
    export type Side = (typeof Side)[keyof typeof Side];
}
