// This file was auto-generated by Fern from our API Definition.

export interface PostOauth2TokenResponse {
    data?: PostOauth2TokenResponse.Data | undefined;
}

export namespace PostOauth2TokenResponse {
    export interface Data {
        /** The access token for API requests */
        access_token?: string | undefined;
        /** Token expiration time in seconds */
        expires_in?: number | undefined;
        /** Token used to refresh the access token */
        refresh_token?: string | undefined;
        /** Comma-separated list of granted scopes */
        scope?: string | undefined;
        /** Type of the token */
        token_type?: string | undefined;
    }
}
