// This file was auto-generated by Fern from our API Definition.

import type * as WhitebitApi from "../../../index.js";

export interface GetDepositWithdrawHistoryResponse {
    limit?: number | undefined;
    offset?: number | undefined;
    records?: WhitebitApi.TransactionHistory[] | undefined;
    /** Total number of transactions, use this for calculating 'limit' and 'offset' */
    total?: number | undefined;
}
