// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../core/index.js";
import * as errors from "../../errors/index.js";
import type * as WhitebitApi from "../index.js";

export class UnavailableForLegalReasonsError extends errors.WhitebitApiError {
    constructor(body: WhitebitApi.ErrorV4, rawResponse?: core.RawResponse) {
        super({
            message: "UnavailableForLegalReasonsError",
            statusCode: 451,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, new.target.prototype);
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, this.constructor);
        }

        this.name = this.constructor.name;
    }
}
