// This file was auto-generated by Fern from our API Definition.

export interface CreateFlexInvestmentResponse {
    data?: CreateFlexInvestmentResponse.Data | undefined;
}

export namespace CreateFlexInvestmentResponse {
    export interface Data {
        /** Transaction ID for the investment */
        transaction_id?: string | undefined;
    }
}
