// This file was auto-generated by Fern from our API Definition.

export interface WithdrawFromFlexInvestmentResponse {
    data?: WithdrawFromFlexInvestmentResponse.Data | undefined;
}

export namespace WithdrawFromFlexInvestmentResponse {
    export interface Data {
        /** Transaction ID for the withdrawal */
        transaction_id?: string | undefined;
    }
}
