// This file was auto-generated by Fern from our API Definition.

export interface ListUnconfirmedSubAccountWithdrawalsResponse {
    /** List of unconfirmed withdrawal transactions. */
    data?: ListUnconfirmedSubAccountWithdrawalsResponse.Data.Item[] | undefined;
    /** Applied limit value. */
    limit?: number | undefined;
    /** Applied offset value. */
    offset?: number | undefined;
}

export namespace ListUnconfirmedSubAccountWithdrawalsResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            /** Transaction external ID (UUID). */
            id?: string | undefined;
            /** Sub-account external ID. */
            subAccountId?: string | undefined;
            /** Currency ticker. */
            currency?: string | undefined;
            /** Withdrawal amount (trailing zeros trimmed). */
            amount?: string | undefined;
            /** Unix timestamp of transaction creation. */
            createdAt?: number | undefined;
        }
    }
}
