// This file was auto-generated by Fern from our API Definition.

import type * as WhitebitApi from "../../../index.js";

export interface ListSubAccountsResponse {
    offset?: number | undefined;
    limit?: number | undefined;
    data?: WhitebitApi.SubAccount[] | undefined;
}
