// This file was auto-generated by Fern from our API Definition.

export interface SubAccountTransferResponse {
    /** External identifier of the transaction. Correlate transfer history responses using the transactionId value. */
    transaction_id?: string | undefined;
}
