// This file was auto-generated by Fern from our API Definition.

export interface GetDepositAddressResponse {
    account?: GetDepositAddressResponse.Account | undefined;
    required?: GetDepositAddressResponse.Required | undefined;
}

export namespace GetDepositAddressResponse {
    export interface Account {
        /** Deposit address */
        address?: string | undefined;
        /** Memo if currency requires memo */
        memo?: string | undefined;
    }

    export interface Required {
        /** Fixed deposit fee */
        fixedFee?: string | undefined;
        /** Flexible fee - is fee that use percent rate */
        flexFee?: Required.FlexFee | undefined;
        /** Max amount of deposit accepted by the exchange. Deposits exceeding this amount are rejected. */
        maxAmount?: string | undefined;
        /** Min amount of deposit accepted by the exchange. Deposits below this amount are rejected. */
        minAmount?: string | undefined;
    }

    export namespace Required {
        /**
         * Flexible fee - is fee that use percent rate
         */
        export interface FlexFee {
            /** Maximum fixed fee charged */
            maxFee?: string | undefined;
            /** Minimum fixed fee charged */
            minFee?: string | undefined;
            /** Percent of deposit as fee */
            percent?: string | undefined;
        }
    }
}
