// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         client_id: "YOUR_CLIENT_ID",
 *         client_secret: "YOUR_CLIENT_SECRET",
 *         token: "REFRESH_TOKEN"
 *     }
 */
export interface PostOauth2RefreshTokenRequest {
    /** The application's client ID */
    client_id: string;
    /** The application's client secret */
    client_secret: string;
    /** The refresh token received from the token endpoint */
    token: string;
}
