// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         client_id: "YOUR_CLIENT_ID",
 *         client_secret: "YOUR_CLIENT_SECRET",
 *         code: "AUTHORIZATION_CODE"
 *     }
 */
export interface PostOauth2TokenRequest {
    /** The application's client ID */
    client_id: string;
    /** The application's client secret */
    client_secret: string;
    /** The authorization code received from the authorization endpoint */
    code: string;
}
