// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         ticker: "USDT",
 *         amount: "25.50",
 *         externalId: "order-100294",
 *         request: "{{request}}",
 *         nonce: 1594297865000
 *     }
 */
export interface CreateExpressWithdrawTokenRequest {
    /**
     * Currency [ticker](/glossary#ticker) to charge. Example: USDT
     *
     * ⚠️ The ticker must be a withdrawal-enabled cryptocurrency; the endpoint rejects [fiat](/glossary#fiat) tickers. Use [Asset Status endpoint](/public/http-v4/asset-status-list) to check the withdrawal status of a currency.
     */
    ticker: string;
    /**
     * Amount to charge in the specified [ticker](/glossary#ticker). Numeric string.
     *
     * ⚠️ The amount converted to USDT-equivalent must not exceed 10,000; the endpoint rejects larger amounts with error code `191`.
     */
    amount: string;
    /** Partner-side reference for the payment (order or invoice identifier), unique per partner account. The identifier powers idempotency and replay protection: a pending `externalId` with an identical `ticker` and `amount` returns the same token; the endpoint rejects an already-paid `externalId` with error code `19`. */
    externalId: string;
    /** Request signature */
    request: string;
    /** Unique request identifier */
    nonce: number;
}
