// This file was auto-generated by Fern from our API Definition.

import type * as WhitebitApi from "../../../../index.js";

/**
 * @example
 *     {
 *         orders: [{
 *                 market: "BTC_USDT",
 *                 orderId: 4326248250
 *             }, {
 *                 market: "ETH_USDT",
 *                 clientOrderId: "my-client-id"
 *             }],
 *         request: "{{request}}",
 *         nonce: 1594297865000
 *     }
 */
export interface CancelBulkOrdersRequest {
    /** Array of orders to cancel. From 1 to 100 items per request. */
    orders: WhitebitApi.BulkCancelOrderItem[];
    request: string;
    nonce: number;
}
