// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         market: "BTC_USDT",
 *         type: ["spot", "margin", "futures"]
 *     }
 */
export interface CancelAllOrdersRequest {
    /** Available [market](/glossary#market). Example: BTC_USDT */
    market?: string;
    /** Order types value. Example: 'spot', 'margin', 'futures' */
    type?: CancelAllOrdersRequest.Type.Item[];
    request?: string;
    nonce?: string;
}

export namespace CancelAllOrdersRequest {
    export type Type = Type.Item[];

    export namespace Type {
        export const Item = {
            Spot: "spot",
            Margin: "margin",
            Futures: "futures",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
