// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetDelistingOrderHistoryRequest {
    /** Trading pair to filter by. Format: `BASE_QUOTE` (e.g., `BTC_USDT`), matching the pattern `^[A-Z0-9]+_[A-Z0-9]+$`. Omit to retrieve delisting orders across all markets. */
    market?: string;
    /** Category filter — distinct from the response `status` field. `filled` returns only reverse close orders (`clientOrderId` prefixed with `delisting-`), which carry `delistingKind` = `reverse` and response `status` = `filled`. `delisting` returns only orders canceled at delisting, which carry `delistingKind` = `canceled` and response `status` = `canceled`. Omit to return both categories merged. */
    status?: GetDelistingOrderHistoryRequest.Status;
    /** Start of the query window as a Unix timestamp in seconds. Default: `now - 30 days`. Must not be later than `endDate`. */
    startDate?: number;
    /** End of the query window as a Unix timestamp in seconds. Default: `now`. Values greater than the current time are clamped to `now`. The maximum span between `startDate` and `endDate` is 31 days. */
    endDate?: number;
    /** Number of records to skip. Default: `0`. The sum of `offset` and `limit` must not exceed 10000. */
    offset?: number;
    /** Maximum number of records to return. Default: `500`. Minimum: `1`. Maximum: `500`. */
    limit?: number;
    request?: string;
    nonce?: number;
}

export namespace GetDelistingOrderHistoryRequest {
    /** Category filter — distinct from the response `status` field. `filled` returns only reverse close orders (`clientOrderId` prefixed with `delisting-`), which carry `delistingKind` = `reverse` and response `status` = `filled`. `delisting` returns only orders canceled at delisting, which carry `delistingKind` = `canceled` and response `status` = `canceled`. Omit to return both categories merged. */
    export const Status = {
        Filled: "filled",
        Delisting: "delisting",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
