// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         orderId: 3134995325,
 *         request: "{{request}}",
 *         nonce: 1594297865000
 *     }
 */
export interface GetOrderDealsRequest {
    /** Identifier of the order to retrieve deals for. */
    orderId: number;
    /** Number of records to skip. Default: `0`. */
    offset?: number;
    /** Maximum number of records to return. Default: `50`. */
    limit?: number;
    request: string;
    nonce: number;
}
