// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         market: "BTC_USDT",
 *         side: "buy",
 *         amount: "0.001",
 *         request: "{{request}}",
 *         nonce: 1594297865000
 *     }
 */
export interface LimitOrderRequest {
    /** Trading pair. Format: `BASE_QUOTE` (e.g., `BTC_USDT`). Query `GET /api/v4/public/markets` for available markets. */
    market: string;
    /** Order side. Allowed values: `buy`, `sell`. */
    side: LimitOrderRequest.Side;
    /** Order quantity in base (stock) currency. Minimum and maximum values are market-dependent. Query `GET /api/v4/public/markets` for `minAmount`, `minTotal`, `maxTotal`. Precision: `stockPrec`. */
    amount: string;
    /** Limit price per unit in quote (money) currency. Required unless `bboRole` is set — the BBO execution method replaces the explicit price. Minimum and maximum values are market-dependent. Precision: `moneyPrec`. */
    price?: string;
    /** Custom client order identifier. Uniqueness is enforced only among the account's open (pending) orders on the same market — once a previous order is filled or canceled, the same identifier can be reused, including on the same market. Contains only letters, numbers, dashes, dots, or underscores. */
    clientOrderId?: string;
    /** Post-only flag. When `true`, the order executes only as a [maker](/glossary#maker) order and the system rejects the order if it would match immediately. Allowed only when `bboRole` is not set. Do not combine with `rpi=true` — RPI orders apply post-only behavior automatically, and a request setting both flags fails validation. Default: `false`. */
    postOnly?: boolean;
    /**
     * Immediate-or-cancel (IOC) flag. When `true`, the matching engine executes all or part of the order immediately and cancels any unfilled portion. Default: `false`.
     *
     * IOC does not support `rpi=true` because RPI uses post-only behavior by design.
     * The API returns error code `40` when a request sets both `ioc=true` and `rpi=true`.
     * IOC cannot be combined with `postOnly=true` (error code `37`), and with `bboRole` it is allowed only for the Counterparty method (`2`).
     *
     * Refer to [Order Parameter Rules](/guides/order-parameter-rules) for unsupported parameter combinations.
     */
    ioc?: boolean;
    /**
     * Best Bid/Offer ([BBO](/glossary#best-bid-offer-bbo)) execution method. The system selects the best market price for execution. `1` = Queue method, `2` = Counterparty method.
     *
     * When `bboRole` is set, `price` is not required — the BBO method determines the execution price. `postOnly` is allowed only when `bboRole` is not set; `ioc` can be combined only with the Counterparty method (`2`). Use method `2` with the `ioc` flag.
     *
     * Refer to [Order Parameter Rules](/guides/order-parameter-rules) for the full interaction rules.
     */
    bboRole?: number;
    /**
     * Self-trade prevention mode. Allowed values: `no` (self-trades allowed), `cb` (cancel both the new and the existing order), `cn` (cancel the new order, keep the existing), `co` (cancel the existing order, place the new one). Default: `no`.
     *
     * Legacy values `cancel_both`, `cancel_new`, `cancel_old` are deprecated: the API accepts the legacy values with identical behavior until a deprecation deadline is announced, then rejects the legacy values. Responses always return the abbreviated form, regardless of which variant the request used.
     *
     * See [Self-Trade Prevention](/platform/self-trade-prevention).
     */
    stp?: LimitOrderRequest.Stp;
    /**
     * Enables Retail Price Improvement (RPI) mode. Default: `false`.
     *
     * RPI orders apply post-only behavior automatically — do not also send an explicit `postOnly=true`: a request combining the two flags fails validation. An RPI order does not support `ioc=true`.
     * The API returns error code `40` when a request sets both `rpi=true` and `ioc=true`.
     * RPI orders do not appear in public order book feeds (`depth`, `bookTicker`). RPI orders are visible only in private active orders and in the exchange UI order book (web/mobile).
     * RPI executions may apply custom fees or rebates, especially when trading via sub-accounts. Use Query Market Fees to verify effective fees.
     *
     * Refer to [Order Parameter Rules](/guides/order-parameter-rules) for unsupported parameter combinations.
     */
    rpi?: boolean;
    /**
     * Retail-source taker flag. When `true`, the order is eligible to match against orders submitted by RPI makers and may receive price improvement at execution. Default: `false`.
     *
     * The Retail flag must be enabled on the account before a private-API request can set `retail=true`. Contact the account manager to enable the Retail flag.
     *
     * The Retail flag cannot be combined with `rpi`. The API returns error code `41` when a request sets both `retail=true` and `rpi=true`.
     *
     * The flag has no effect on a `postOnly=true` order. Post-only orders are [makers](/glossary#maker); only takers carry the retail designation.
     *
     * Refer to [Retail flag](/glossary#retail-flag) and [Order Parameter Rules](/guides/order-parameter-rules) for unsupported parameter combinations.
     */
    retail?: boolean;
    request: string;
    nonce: number;
}

export namespace LimitOrderRequest {
    /** Order side. Allowed values: `buy`, `sell`. */
    export const Side = {
        Buy: "buy",
        Sell: "sell",
    } as const;
    export type Side = (typeof Side)[keyof typeof Side];
    /**
     * Self-trade prevention mode. Allowed values: `no` (self-trades allowed), `cb` (cancel both the new and the existing order), `cn` (cancel the new order, keep the existing), `co` (cancel the existing order, place the new one). Default: `no`.
     *
     * Legacy values `cancel_both`, `cancel_new`, `cancel_old` are deprecated: the API accepts the legacy values with identical behavior until a deprecation deadline is announced, then rejects the legacy values. Responses always return the abbreviated form, regardless of which variant the request used.
     *
     * See [Self-Trade Prevention](/platform/self-trade-prevention).
     */
    export const Stp = {
        No: "no",
        Cb: "cb",
        Cn: "cn",
        Co: "co",
    } as const;
    export type Stp = (typeof Stp)[keyof typeof Stp];
}
