// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         market: "BTC_USDT",
 *         request: "{{request}}",
 *         nonce: "{{nonce}}"
 *     }
 */
export interface ModifyOrderRequest {
    /** Active order id. Required if client_order_id is not set. */
    order_id?: number;
    /** Identifier should be unique and contain letters, dashes, numbers, dots or underscores. Required if order_id is not set. */
    client_order_id?: string;
    /** Available [market](/glossary#market). Example: BTC_USDT */
    market: string;
    /** Amount of [stock](/glossary#stock) currency to buy or sell. Example: '0.001' or 0.001 */
    amount?: string;
    /** Total of [money](/glossary#money) currency to buy or sell. Example: '0.001' or 0.001 */
    total?: string;
    /** Price in [money](/glossary#money) currency. Example: '9800' or 9800 */
    price?: string;
    /** Activation price in [money](/glossary#money) currency. Example: '10000' or 10000 */
    activationPrice?: string;
    request: string;
    nonce: string;
}
