// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         market: "BTC_USDT",
 *         timeout: "60"
 *     }
 */
export interface SetKillSwitchRequest {
    /** Available [market](/glossary#market). Example: BTC_USDT */
    market: string;
    /** Timer value. Example: '5'-'600' or null */
    timeout: string;
    /** Order types value. Example: 'spot', 'margin', 'futures' or null */
    types?: SetKillSwitchRequest.Types.Item[];
    request?: string;
    nonce?: string;
}

export namespace SetKillSwitchRequest {
    export type Types = Types.Item[];

    export namespace Types {
        export const Item = {
            Spot: "spot",
            Margin: "margin",
            Futures: "futures",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
