// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         market: "BTC_USDT",
 *         timeout: "60"
 *     }
 */
export interface SetKillSwitchRequest {
    /** Available [market](/glossary#market). Example: BTC_USDT */
    market: string;
    /** Timer value. Example: '5'-'600' or null */
    timeout: string;
    /** Order types to target. Valid values: "spot" — standard spot orders. "margin" — marginal orders placed on spot markets. Note: the "margin" value is not the same as the collateral account balance; "collateral" in other endpoints refers to the funding account, whereas "margin" here refers specifically to the order type. "futures" — marginal orders placed on futures markets (e.g., BTC_PERP). If omitted, the API targets all order types. */
    types?: SetKillSwitchRequest.Types.Item[];
    request?: string;
    nonce?: number;
}

export namespace SetKillSwitchRequest {
    export type Types = Types.Item[];

    export namespace Types {
        export const Item = {
            Spot: "spot",
            Margin: "margin",
            Futures: "futures",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
