// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         market: "BTC_USDT",
 *         side: "buy",
 *         amount: "0.001",
 *         price: "9800",
 *         activation_price: "10000",
 *         request: "{{request}}",
 *         nonce: "{{nonce}}"
 *     }
 */
export interface StopLimitOrderRequest {
    /** Available [market](/glossary#market). Example: BTC_USDT */
    market: string;
    /** Order type. Variables: 'buy' / 'sell' Example: 'buy' */
    side: StopLimitOrderRequest.Side;
    /** Amount of [stock](/glossary#stock) currency to buy or sell. Example: '0.001' or 0.001 */
    amount: string;
    /** Price in [money](/glossary#money) currency. Example: '9800' or 9800 */
    price: string;
    /** Activation price in [money](/glossary#money) currency. Example: '10000' or 10000 */
    activation_price: string;
    /** Identifier should be unique and contain letters, dashes, numbers, dots or underscores. The identifier must be unique. */
    client_order_id?: string;
    /** When the [BBO](/glossary#bbo) option is activated for Limit orders, the system selects the best market prices for execution. Variables: 1 - Queue Method / 2 - Counterparty Method. */
    bboRole?: number;
    /** Self trade prevention mode. Variables: 'no' / 'cancel_both' / 'cancel_new' / 'cancel_old'. Example: 'no'. */
    stp?: StopLimitOrderRequest.Stp;
    request: string;
    nonce: string;
}

export namespace StopLimitOrderRequest {
    /** Order type. Variables: 'buy' / 'sell' Example: 'buy' */
    export const Side = {
        Buy: "buy",
        Sell: "sell",
    } as const;
    export type Side = (typeof Side)[keyof typeof Side];
    /** Self trade prevention mode. Variables: 'no' / 'cancel_both' / 'cancel_new' / 'cancel_old'. Example: 'no'. */
    export const Stp = {
        No: "no",
        CancelBoth: "cancel_both",
        CancelNew: "cancel_new",
        CancelOld: "cancel_old",
    } as const;
    export type Stp = (typeof Stp)[keyof typeof Stp];
}
