// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         market: "BTC_USDT",
 *         side: "buy",
 *         amount: "0.01",
 *         activation_price: "10000",
 *         request: "{{request}}",
 *         nonce: "{{nonce}}"
 *     }
 */
export interface StopMarketOrderRequest {
    /** Available [market](/glossary#market). Example: BTC_USDT */
    market: string;
    /** Order type. Variables: 'buy' / 'sell' Example: 'buy' */
    side: StopMarketOrderRequest.Side;
    /** Amount of [money](/glossary#money) currency to buy or amount in [stock](/glossary#stock) currency to sell. Example: '0.01' or 0.01 for buy and '0.0001' for sell. */
    amount: string;
    /** Activation price in [money](/glossary#money) currency. Example: '10000' or 10000 */
    activation_price: string;
    /** Identifier should be unique and contain letters, dashes, numbers, dots or underscores. The identifier must be unique. */
    client_order_id?: string;
    /** Self trade prevention mode. Variables: 'no' / 'cancel_both' / 'cancel_new' / 'cancel_old'. Example: 'no'. */
    stp?: StopMarketOrderRequest.Stp;
    request: string;
    nonce: string;
}

export namespace StopMarketOrderRequest {
    /** Order type. Variables: 'buy' / 'sell' Example: 'buy' */
    export const Side = {
        Buy: "buy",
        Sell: "sell",
    } as const;
    export type Side = (typeof Side)[keyof typeof Side];
    /** Self trade prevention mode. Variables: 'no' / 'cancel_both' / 'cancel_new' / 'cancel_old'. Example: 'no'. */
    export const Stp = {
        No: "no",
        CancelBoth: "cancel_both",
        CancelNew: "cancel_new",
        CancelOld: "cancel_old",
    } as const;
    export type Stp = (typeof Stp)[keyof typeof Stp];
}
