// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface TradeAccountBalanceRequest {
    /** Currency's [ticker](/glossary#ticker). Example: BTC */
    ticker?: string;
    request?: string;
    nonce?: string;
}
