// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         market: "BTC_USDT"
 *     }
 */
export interface GetMarketFeeRequest {
    /**
     * Market to query.
     *
     * If the request includes the `market` parameter, the system returns fees for the specified market only.
     *
     * When fee values are identical across markets, the response contains identical values regardless of the specified market.
     *
     * Example: BTC_USDT
     */
    market: string;
}
