// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         market: "BTC_USDT"
 *     }
 */
export interface GetMarketFeeRequest {
    /** Optional. Currently ignored by the API — all market fees are returned regardless of the value provided. Retained for backward compatibility. Example: BTC_USDT */
    market?: string;
}
