// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         accounts: ["my_miner_01", "my_miner_02"],
 *         name: "monitoring_link",
 *         permissions: ["dashboard", "workers"],
 *         liveUntil: "1h"
 *     }
 */
export interface CreateMiningWatcherLinkRequest {
    /** Array of mining account names */
    accounts: string[];
    /** Link name (alphanumeric and underscores only) */
    name: string;
    /** Array of permissions */
    permissions: CreateMiningWatcherLinkRequest.Permissions.Item[];
    /** Expiration period */
    liveUntil: CreateMiningWatcherLinkRequest.LiveUntil;
}

export namespace CreateMiningWatcherLinkRequest {
    export type Permissions = Permissions.Item[];

    export namespace Permissions {
        export const Item = {
            Dashboard: "dashboard",
            Rewards: "rewards",
            Workers: "workers",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }

    /** Expiration period */
    export const LiveUntil = {
        OneH: "1h",
        TwentyFourH: "24h",
        SevenD: "7d",
        Always: "always",
    } as const;
    export type LiveUntil = (typeof LiveUntil)[keyof typeof LiveUntil];
}
