// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "my_miner_01",
 *         request: "{{request}}",
 *         nonce: "{{nonce}}"
 *     }
 */
export interface CreateMiningAccountRequest {
    /** Mining pool account name. Must be unique. Alphanumeric characters and underscores allowed. */
    name: string;
    /** Optional referral code for account creation */
    referralCode?: string;
    /** Request signature */
    request: string;
    /** Unique request identifier */
    nonce: string;
}
