// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         request: "{{request}}",
 *         nonce: 1594297865000
 *     }
 */
export interface GetMiningAccountsRequest {
    /** Optional filter to search for a specific mining account name (exact match) */
    name?: string;
    /** Request signature */
    request: string;
    /** Unique request identifier */
    nonce: number;
}
