// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account: "miner123"
 *     }
 */
export interface GetMiningHashrateRequest {
    /** Mining pool account */
    account: string;
    /** Unix timestamp of starting point */
    from?: number;
    /** Unix timestamp of final point */
    to?: number;
    /** Timestamp interval */
    interval?: GetMiningHashrateRequest.Interval;
}

export namespace GetMiningHashrateRequest {
    /** Timestamp interval */
    export const Interval = {
        FiveM: "5m",
        OneH: "1h",
        TwentyFourH: "24h",
    } as const;
    export type Interval = (typeof Interval)[keyof typeof Interval];
}
