// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         accountName: "my_miner_01"
 *     }
 */
export interface GetMiningPayoutDestinationRequest {
    /** Mining pool account name */
    accountName: string;
}
