// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account: "my_miner_01"
 *     }
 */
export interface GetMiningWorkerNamesRequest {
    /** Mining pool account name */
    account: string;
    /** Pagination offset */
    offset?: number;
    /** Pagination limit */
    limit?: number;
}
