// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account: "my_miner_01"
 *     }
 */
export interface ListMiningWatcherLinksRequest {
    /** Mining pool account name */
    account: string;
}
