// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         accountName: "my_miner_01",
 *         destination: "main_balance"
 *     }
 */
export interface SetMiningPayoutDestinationRequest {
    /** Mining pool account name */
    accountName: string;
    /** Payout destination type */
    destination: SetMiningPayoutDestinationRequest.Destination;
    /** External BTC address. Required when destination is external_address. Supports all standard Bitcoin address formats. */
    address?: string;
}

export namespace SetMiningPayoutDestinationRequest {
    /** Payout destination type */
    export const Destination = {
        MainBalance: "main_balance",
        ExternalAddress: "external_address",
    } as const;
    export type Destination = (typeof Destination)[keyof typeof Destination];
}
