// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         market: "BTC_USDT",
 *         otoId: 117703764514,
 *         request: "{{request}}",
 *         nonce: "{{nonce}}"
 *     }
 */
export interface CancelOtoOrderRequest {
    market: string;
    otoId: number;
    request: string;
    nonce: string;
}
