// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         market: "BTC_USDT",
 *         orderId: 117703764514,
 *         request: "{{request}}",
 *         nonce: 1594297865000
 *     }
 */
export interface CancelOcoOrderRequest {
    market: string;
    orderId: number;
    request: string;
    nonce: number;
}
