// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         positionId: 123,
 *         positionSide: "LONG",
 *         market: "BTC_USDT",
 *         request: "{{request}}",
 *         nonce: "{{nonce}}"
 *     }
 */
export interface ClosePositionRequest {
    positionId: number;
    positionSide?: ClosePositionRequest.PositionSide;
    market: string;
    request: string;
    nonce: string;
}

export namespace ClosePositionRequest {
    export const PositionSide = {
        Long: "LONG",
        Short: "SHORT",
        Both: "BOTH",
    } as const;
    export type PositionSide = (typeof PositionSide)[keyof typeof PositionSide];
}
