// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         ticker: "BTC",
 *         request: "{{request}}",
 *         nonce: "{{nonce}}"
 *     }
 */
export interface CollateralAccountBalanceSummaryRequest {
    /**
     * Filter by requested asset. For example: BTC
     *
     * If not specified, returns summary for all assets.
     */
    ticker?: string;
    /** Request signature */
    request?: string;
    /** Unique request identifier */
    nonce?: string;
}
