// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         request: "{{request}}",
 *         nonce: 1594297865000
 *     }
 */
export interface CollateralAccountSummaryRequest {
    request?: string;
    nonce?: number;
}
