// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         market: "BTC_USDT",
 *         side: "buy",
 *         amount: "0.01",
 *         client_order_id: "order1987111",
 *         request: "{{request}}",
 *         nonce: "{{nonce}}"
 *     }
 */
export interface CreateCollateralMarketOrderRequest {
    market: string;
    side: CreateCollateralMarketOrderRequest.Side;
    amount: string;
    client_order_id?: string;
    stopLoss?: string;
    takeProfit?: string;
    positionSide?: CreateCollateralMarketOrderRequest.PositionSide;
    request: string;
    nonce: string;
}

export namespace CreateCollateralMarketOrderRequest {
    export const Side = {
        Buy: "buy",
        Sell: "sell",
    } as const;
    export type Side = (typeof Side)[keyof typeof Side];
    export const PositionSide = {
        Long: "LONG",
        Short: "SHORT",
        Both: "BOTH",
    } as const;
    export type PositionSide = (typeof PositionSide)[keyof typeof PositionSide];
}
