// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         market: "BTC_USDT",
 *         side: "buy",
 *         amount: "0.001",
 *         price: "40000",
 *         activation_price: "40000",
 *         stopLoss: "30000",
 *         takeProfit: "50000",
 *         client_order_id: "order1987111",
 *         positionSide: "LONG",
 *         request: "{{request}}",
 *         nonce: "{{nonce}}"
 *     }
 */
export interface CreateCollateralStopLimitOrderRequest {
    market: string;
    side: CreateCollateralStopLimitOrderRequest.Side;
    amount: string;
    price: string;
    activation_price: string;
    stopLoss?: string;
    takeProfit?: string;
    client_order_id?: string;
    positionSide?: CreateCollateralStopLimitOrderRequest.PositionSide;
    request: string;
    nonce: string;
}

export namespace CreateCollateralStopLimitOrderRequest {
    export const Side = {
        Buy: "buy",
        Sell: "sell",
    } as const;
    export type Side = (typeof Side)[keyof typeof Side];
    export const PositionSide = {
        Long: "LONG",
        Short: "SHORT",
        Both: "BOTH",
    } as const;
    export type PositionSide = (typeof PositionSide)[keyof typeof PositionSide];
}
