// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         market: "BTC_USDT",
 *         side: "buy",
 *         amount: "0.01",
 *         price: "40000",
 *         client_order_id: "order1987111",
 *         stopLoss: "50000",
 *         takeProfit: "30000",
 *         postOnly: false,
 *         ioc: false,
 *         rpi: true,
 *         positionSide: "LONG",
 *         request: "{{request}}",
 *         nonce: "{{nonce}}"
 *     }
 */
export interface CreateCollateralLimitOrderRequest {
    /** Available margin [market](/glossary#market). Example: BTC_USDT */
    market: string;
    /** Order type. Variables: 'buy' / 'sell'. For open long position use **buy**, for short **sell**. */
    side: CreateCollateralLimitOrderRequest.Side;
    /** Amount of [stock](/glossary#stock) currency to buy or sell. */
    amount: string;
    /** Price in [money](/glossary#money) currency. Example: '9800' */
    price: string;
    /** Identifier should be unique and contain letters, dashes, numbers, dots or underscores. */
    client_order_id?: string;
    /**
     * Stop loss price.
     *
     * When provided, the system creates an [OTO](/glossary#one-triggers-the-other-oto) order with a stop loss condition.
     */
    stopLoss?: string;
    /**
     * Take profit price.
     *
     * When provided, the system creates an [OTO](/glossary#one-triggers-the-other-oto) order with a take profit condition.
     */
    takeProfit?: string;
    /** Orders are guaranteed to be the [maker](/glossary#maker) order when [executed](/glossary#finished-orders). */
    postOnly?: boolean;
    /** An immediate or cancel order (IOC) is an order that attempts to execute all or part immediately and then cancels any unfilled portion. */
    ioc?: boolean;
    /**
     * Enables Retail Price Improvement (RPI) mode.
     *
     * RPI orders are post-only by design and cannot be used with `ioc=true`. The API returns error code `37` when both `rpi=true` and `ioc=true` are used.
     */
    rpi?: boolean;
    /** Defines the position direction when hedge mode is enabled. See [positionSide](/glossary#position-side) */
    positionSide?: CreateCollateralLimitOrderRequest.PositionSide;
    request: string;
    nonce: string;
}

export namespace CreateCollateralLimitOrderRequest {
    /** Order type. Variables: 'buy' / 'sell'. For open long position use **buy**, for short **sell**. */
    export const Side = {
        Buy: "buy",
        Sell: "sell",
    } as const;
    export type Side = (typeof Side)[keyof typeof Side];
    /** Defines the position direction when hedge mode is enabled. See [positionSide](/glossary#position-side) */
    export const PositionSide = {
        Long: "LONG",
        Short: "SHORT",
        Both: "BOTH",
    } as const;
    export type PositionSide = (typeof PositionSide)[keyof typeof PositionSide];
}
