// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         startDate: 1778000000,
 *         endDate: 1778100000,
 *         limit: 50,
 *         offset: 0,
 *         request: "{{request}}",
 *         nonce: 1594297865000
 *     }
 */
export interface GetClosedPositionsPnlRequest {
    /** Start of the query window as a Unix timestamp in seconds, applied to the position close time. Optional, no default. Must be ≤ `endDate`. */
    startDate?: number;
    /** End of the query window as a Unix timestamp in seconds, applied to the position close time. Optional, no default. Must be ≥ `startDate` and ≤ `now + 1s`. */
    endDate?: number;
    /** Maximum number of records to return. Default: `50`. Minimum: `1`. Maximum: `100`. */
    limit?: number;
    /** Number of records to skip. Default: `0`. The sum of `offset` and `limit` must not exceed 10000. */
    offset?: number;
    request?: string;
    nonce?: number;
}
