// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         market: "BTC_PERP",
 *         limit: 100,
 *         offset: 0,
 *         request: "{{request}}",
 *         nonce: "{{nonce}}"
 *     }
 */
export interface GetFundingHistoryRequest {
    /**
     * Filter by specific market. For example: BTC_PERP
     *
     * If not specified, returns funding history for all markets.
     */
    market?: string;
    /** Number of records to return */
    limit?: number;
    /** Number of records to skip */
    offset?: number;
    /** Request signature */
    request?: string;
    /** Unique request identifier */
    nonce?: string;
}
