// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         market: "BTC_USDT",
 *         positionId: 1,
 *         request: "{{request}}",
 *         nonce: "{{nonce}}"
 *     }
 */
export interface GetPositionsHistoryRequest {
    market?: string;
    positionId?: number;
    request?: string;
    nonce?: string;
}
