// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         hedgeMode: true,
 *         request: "{{request}}",
 *         nonce: "{{nonce}}"
 *     }
 */
export interface UpdateHedgeModeRequest {
    hedgeMode: boolean;
    request: string;
    nonce: string;
}
