// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         ticker: "XLM",
 *         request: "{{request}}",
 *         nonce: 1594297865000
 *     }
 *
 * @example
 *     {
 *         ticker: "USDT",
 *         network: "ERC20",
 *         request: "{{request}}",
 *         nonce: 1594297865000
 *     }
 *
 * @example
 *     {
 *         ticker: "BTC",
 *         type: "bech32",
 *         request: "{{request}}",
 *         nonce: 1594297865000
 *     }
 */
export interface CreateNewAddressRequest {
    /** Currency's ticker. */
    ticker: string;
    /** Currency's network (for multinetwork currencies). Example: OMNI or TRC20 or ERC20. For USDT default network is ERC20(ETH). */
    network?: string;
    /** Address type, available for specific currencies list (see address types table in endpoint description) */
    type?: CreateNewAddressRequest.Type;
    /** Request signature */
    request: string;
    /** Unique request identifier */
    nonce: number;
}

export namespace CreateNewAddressRequest {
    /** Address type, available for specific currencies list (see address types table in endpoint description) */
    export const Type = {
        P2ShSegwit: "p2sh-segwit",
        Bech32: "bech32",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
