// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         cardNumber: "4111111111111111"
 *     }
 */
export interface IssueCardTokenRequest {
    /** Target card number */
    cardNumber: string;
}
