// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         transactionId: "54bffeb7-7a8f-43f8-bcd8-f14ec10fee85",
 *         address: "0x1234567890abcdef1234567890abcdef12345678",
 *         request: "{{request}}",
 *         nonce: 1594297865000
 *     }
 */
export interface RefundDepositRequest {
    /** Transaction UUID of the deposit. Obtain from the [deposit.canceled](/platform/webhook) webhook (`uniqueId` field) or from the deposit/withdraw history in the WhiteBIT interface. */
    transactionId: string;
    /** Destination wallet address for the refund. The address must support the same network and asset as the original deposit. Cannot be a WhiteBIT address. Does not have to match the original deposit address. */
    address: string;
    /** Base64-encoded request body. See the [authentication guide](/private/http-auth) for signature generation details. */
    request: string;
    /** A unique identifier for the request. Use a monotonically increasing value such as a Unix timestamp in milliseconds. */
    nonce: number;
}
