// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         plan: "8f2e9d3c-1a4b-4c2d-9e5f-6a7b8c9d0e1f",
 *         amount: "1000.500000",
 *         withReinvest: true,
 *         request: "{{request}}",
 *         nonce: 1594297865000
 *     }
 */
export interface CreateFlexInvestmentRequest {
    /** Plan external ID (UUID). */
    plan: string;
    /** Investment amount. */
    amount: string;
    /** Enable auto-reinvestment. */
    withReinvest?: boolean;
    /** Request signature */
    request: string;
    /** Unique request identifier */
    nonce: number;
}
