// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         limit: 50,
 *         offset: 0,
 *         ticker: "USDT",
 *         request: "{{request}}",
 *         nonce: 1594297865000
 *     }
 */
export interface GetFlexPlansRequest {
    /** Pagination limit. */
    limit?: number;
    /** Pagination offset. */
    offset?: number;
    /** Filter by currency [ticker](/glossary#ticker). Example: USDT */
    ticker?: string;
    /** Request signature */
    request: string;
    /** Unique request identifier */
    nonce: number;
}
