// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         limit: 50,
 *         offset: 0,
 *         plan: "8f2e9d3c-1a4b-4c2d-9e5f-6a7b8c9d0e1f",
 *         investment: "inv_123",
 *         transaction: "tx_456",
 *         dateFrom: 1640995200,
 *         dateTo: 1641081600,
 *         request: "{{request}}",
 *         nonce: 1594297865000
 *     }
 */
export interface GetFlexPaymentHistoryRequest {
    /** Pagination limit. */
    limit?: number;
    /** Pagination offset. */
    offset?: number;
    /** Filter by plan ID (UUID). */
    plan?: string;
    /** Filter by investment ID. */
    investment?: string;
    /** Filter by transaction ID. */
    transaction?: string;
    /** Filter from date (timestamp). */
    dateFrom?: number;
    /** Filter to date (timestamp). */
    dateTo?: number;
    /** Request signature */
    request: string;
    /** Unique request identifier */
    nonce: number;
}
