// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         limit: 100,
 *         offset: 0,
 *         ticker: "USDT",
 *         plan: "8f2e9d3c-1a4b-4c2d-9e5f-6a7b8c9d0e1f",
 *         investment: "invest_id_123",
 *         investmentStatus: 1,
 *         request: "{{request}}",
 *         nonce: "{{nonce}}"
 *     }
 */
export interface GetUserFlexInvestmentsRequest {
    /** Pagination limit. Default: 100. */
    limit?: number;
    /** Pagination offset. Default: 0. */
    offset?: number;
    /** Filter by currency [ticker](/glossary#ticker). Example: USDT. */
    ticker?: string;
    /** Filter by plan ID (UUID). */
    plan?: string;
    /** Filter by investment ID. */
    investment?: string;
    /** Filter by status (1=ACTIVE, 0=CLOSED). */
    investmentStatus?: number;
    /** Request signature */
    request: string;
    /** Unique request identifier */
    nonce: string;
}
