// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         plan: "8f2e9d3c-1a4b-4c2d-9e5f-6a7b8c9d0e1f",
 *         amount: "500.250000",
 *         request: "{{request}}",
 *         nonce: "{{nonce}}"
 *     }
 */
export interface WithdrawFromFlexInvestmentRequest {
    /** Plan external ID (UUID). */
    plan: string;
    /** Withdrawal amount. */
    amount: string;
    /** Request signature */
    request: string;
    /** Unique request identifier */
    nonce: string;
}
